//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDMOVIE_H
#define UIFLOWWNDMOVIE_H

#include "UIFramework.h"

#define UIFlowWndMovieRecordExtendCrash  0x101
#define UIFlowWndMovieRecordCrash        0x102
#define UIFlowWndMovieRecordEMR          0x103
extern VControl UIFlowWndMovieCtrl;//Panel type

extern VControl UIFlowWndMovie_Panel_Normal_DisplayCtrl;//Panel type

extern VControl UIFlowWndMovie_Static_cameraCtrl;//Static type

extern VControl UIFlowWndMovie_Status_CyclicRecCtrl;//Status type

typedef enum {
	UIFlowWndMovie_Status_CyclicRec_ICONID_NULL,
	UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_1MIN,
	UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_3MIN,
	UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_5MIN,
	UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_10MIN,
	UIFlowWndMovie_Status_CyclicRec_MAX
} UIFlowWndMovie_Status_CyclicRec_Setting;

extern VControl UIFlowWndMovie_Status_MotionDetCtrl;//Status type

typedef enum {
	UIFlowWndMovie_Status_MotionDet_ICONID_NULL,
	UIFlowWndMovie_Status_MotionDet_ICON_MOTION_DET_ON,
	UIFlowWndMovie_Status_MotionDet_MAX
} UIFlowWndMovie_Status_MotionDet_Setting;

extern VControl UIFlowWndMovie_Status_batteryCtrl;//Status type

typedef enum {
	UIFlowWndMovie_Status_battery_ICON_BATTERY_FULL,
	UIFlowWndMovie_Status_battery_ICON_BATTERY_MED,
	UIFlowWndMovie_Status_battery_ICON_BATTERY_LOW,
	UIFlowWndMovie_Status_battery_ICON_BATTERY_EMPTY,
	UIFlowWndMovie_Status_battery_ICON_BATTERY_ZERO,
	UIFlowWndMovie_Status_battery_ICON_BATTERY_CHARGE,
	UIFlowWndMovie_Status_battery_MAX
} UIFlowWndMovie_Status_battery_Setting;

extern VControl UIFlowWndMovie_YMD_StaticCtrl;//Static type

extern VControl UIFlowWndMovie_HMS_StaticCtrl;//Static type

extern VControl UIFlowWndMovie_Status_RECCtrl;//Status type

typedef enum {
	UIFlowWndMovie_Status_REC_ICON_REC_TRANSPAENT,
	UIFlowWndMovie_Status_REC_ICON_REC_ELLIPSE,
	UIFlowWndMovie_Status_REC_MAX
} UIFlowWndMovie_Status_REC_Setting;

extern VControl UIFlowWndMovie_Status_StorageCtrl;//Status type

typedef enum {
	UIFlowWndMovie_Status_Storage_ICON_INTERNAL_FLASH,
	UIFlowWndMovie_Status_Storage_ICON_SD_CARD,
	UIFlowWndMovie_Status_Storage_ICON_SD_LOCK,
	UIFlowWndMovie_Status_Storage_MAX
} UIFlowWndMovie_Status_Storage_Setting;

extern VControl UIFlowWndMovie_Static_timeCtrl;//Static type

extern VControl UIFlowWndMovie_Static_maxtimeCtrl;//Static type

extern VControl UIFlowWndMovie_Static_resolutionCtrl;//Static type

extern VControl UIFlowWndMovie_Zoom_StaticCtrl;//Static type

extern VControl UIFlowWndMovie_StatusICN_EVCtrl;//Status type 



typedef enum {
	UIFlowWndMovie_StatusICN_EV_ICON_EV_P2P0,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P6,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P3,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P0,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P6,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P3,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P0,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_M0P3,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_M0P6,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P0,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P3,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P6,
	UIFlowWndMovie_StatusICN_EV_ICON_EV_M2P0,
	UIFlowWndMovie_StatusICN_EV_MAX
} UIFlowWndMovie_StatusICN_EV_Setting;

extern VControl UIFlowWndMovie_Status_HDRCtrl;//Status type

typedef enum {
	UIFlowWndMovie_Status_HDR_ICONID_NULL,
	UIFlowWndMovie_Status_HDR_ICON_HDR,
	UIFlowWndMovie_Status_HDR_MAX
} UIFlowWndMovie_Status_HDR_Setting;

extern VControl UIFlowWndMovie_Status_WIFICtrl;//Status type

typedef enum {
	UIFlowWndMovie_Status_WIFI_ICON_WIFI_OFF,
	UIFlowWndMovie_Status_WIFI_ICON_WIFI_ON,
	UIFlowWndMovie_Status_WIFI_ICON_CLOUD_ON,
	UIFlowWndMovie_Status_WIFI_MAX
} UIFlowWndMovie_Status_WIFI_Setting;

extern VControl UIFlowWndMovie_StaticIcon_PIMCCtrl;//Static type 

extern VControl UIFlowWndMovie_ALG_DrawCtrl;//Panel type 

extern VControl UIFlowWndMovie_PNL_FDFrameCtrl;//Panel type

extern VControl UIFlowWndMovie_ADAS_DrawingLineCtrl;//Panel type

extern VControl UIFlowWndMovie_Status_ParkingCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Parking_ICON_BSD_OFF,
UIFlowWndMovie_Status_Parking_ICON_BSD_ON,
UIFlowWndMovie_Status_Parking_MAX
}UIFlowWndMovie_Status_Parking_Setting;

extern VControl UIFlowWndMovie_Status_MicroPhoneCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_MicroPhone_ICON_SOUND_REC_OFF,
UIFlowWndMovie_Status_MicroPhone_ICON_SOUND_REC_ON,
UIFlowWndMovie_Status_MicroPhone_MAX
}UIFlowWndMovie_Status_MicroPhone_Setting;

extern VControl UIFlowWndMovie_Static_CardFreeCapacityCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_LockCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Lock_ICONID_NULL,
UIFlowWndMovie_Status_Lock_ICON_LOCK,
UIFlowWndMovie_Status_Lock_MAX
}UIFlowWndMovie_Status_Lock_Setting;

extern VControl UIFlowWndMovie_Status_SnapCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Snap_ICON_P12H,
UIFlowWndMovie_Status_Snap_ICON_P24H,
UIFlowWndMovie_Status_Snap_ICON_P48H,
UIFlowWndMovie_Status_Snap_MAX
}UIFlowWndMovie_Status_Snap_Setting;

extern VControl UIFlowWndMovie_StaticTXT_SSIDCtrl;//Static type 

extern VControl UIFlowWndMovie_StaticTXT_KeyCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_GsensorCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Gsensor_ICON_G_SENSOR_OFF,
UIFlowWndMovie_Status_Gsensor_ICON_G_SENSOR_LOW,
UIFlowWndMovie_Status_Gsensor_ICON_G_SENSOR_MID,
UIFlowWndMovie_Status_Gsensor_ICON_G_SENSOR_HIGH,
UIFlowWndMovie_Status_Gsensor_MAX
}UIFlowWndMovie_Status_Gsensor_Setting;

extern VControl UIFlowWndMovie_Status_GPSCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_GPS_ICONID_NULL,
UIFlowWndMovie_Status_GPS_ICON_LOCATION,
UIFlowWndMovie_Status_GPS_MAX
}UIFlowWndMovie_Status_GPS_Setting;

extern VControl UIFlowWndMovie_ADAS_Alert_DisplayCtrl;//Panel type 

//#NT#2016/03/02#Lincy Lin -begin
//#NT#Support object tracking function
extern VControl UIFlowWndMovie_OT_DrawRectCtrl;//Panel type
//#NT#2016/03/02#Lincy Lin -end
//#NT#2016/05/26#David Tsai -begin
//#NT#Support tampering detection
extern VControl UIFlowWndMovie_TD_DrawRectCtrl;//Panel type
//#NT#2016/05/26#David Tsai -end

extern VControl UIFlowWndMovie_StatusICN_LDWS_AlertCtrl;//Status type

typedef enum {
	UIFlowWndMovie_StatusICN_LDWS_Alert_ICON_LDWS_LEFT_ALERT,
	UIFlowWndMovie_StatusICN_LDWS_Alert_ICON_LDWS_RIGHT_ALERT,
	UIFlowWndMovie_StatusICN_LDWS_Alert_MAX
} UIFlowWndMovie_StatusICN_LDWS_Alert_Setting;

extern VControl UIFlowWndMovie_StatusICN_FCWS_AlertCtrl;//Status type

typedef enum {
	UIFlowWndMovie_StatusICN_FCWS_Alert_ICON_FCW_FAR_ALERT,
	UIFlowWndMovie_StatusICN_FCWS_Alert_ICON_FCW_NEAR_ALERT,
	UIFlowWndMovie_StatusICN_FCWS_Alert_MAX
} UIFlowWndMovie_StatusICN_FCWS_Alert_Setting;

extern VControl UIFlowWndMovie_StatusICN_SNG_AlertCtrl;//Status type

typedef enum {
	UIFlowWndMovie_StatusICN_SNG_Alert_ICON_SNG_ALERT,
	UIFlowWndMovie_StatusICN_SNG_Alert_MAX
} UIFlowWndMovie_StatusICN_SNG_Alert_Setting;

//---------------------UIFlowWndMovieCtrl User Export---------------------------
#endif
