//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoSharpnessRes.c"
#include "UIMenuWndPhotoSharpness.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoSharpnessCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOSHARPNESS_ERROR_MSG        1
#define _UIMENUWNDPHOTOSHARPNESS_TRACE_MSG        0

#if (_UIMENUWNDPHOTOSHARPNESS_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoSharpnessErrMsg(...)            debug_msg ("^R UIMenuWndPhotoSharpness: "__VA_ARGS__)
#else
#define UIMenuWndPhotoSharpnessErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOSHARPNESS_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoSharpnessTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoSharpness: "__VA_ARGS__)
#else
#define UIMenuWndPhotoSharpnessTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoSharpnessCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoSharpnessCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoSharpnessCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoSharpnessCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoSharpnessCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoSharpness)
CTRL_LIST_ITEM(UIMenuWndPhotoSharpness_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoSharpness_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoSharpnessCtrl Event---------------------------
INT32 UIMenuWndPhotoSharpness_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSharpness_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSharpness_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSharpness_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoSharpness)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoSharpness_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoSharpness_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoSharpness_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoSharpness_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoSharpness_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_SHARPNESS))
	{
		case SHARPNESS_SHARP:  
			Data = 0;
			break;
		case SHARPNESS_NORMAL:  
			Data = 1;
			break;	
		case SHARPNESS_SOFT:  
			Data = 2;
			break;				
		default:
			Data = 1;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoSharpness_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSharpness_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPhotoSharpness_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSharpness_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoSharpnessCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoSharpness_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoSharpness_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoSharpness_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoSharpness_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoSharpness_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoSharpness_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSharpness_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSharpness_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoSharpness_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoSharpness_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoSharpness_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoSharpness_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoSharpness_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSharpness_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSharpness_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = SHARPNESS_SHARP;
			break;

		case 1:
			uiSelItem = SHARPNESS_NORMAL;
			break;

		case 2:
			uiSelItem = SHARPNESS_SOFT;
			break;
			
		default:
			uiSelItem = SHARPNESS_NORMAL;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_SHARPNESS, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndPhotoSharpnessCtrl, 0);

    return NVTEVT_CONSUME;
}
