//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOBURST_H
#define UIMENUWNDPHOTOBURST_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoBurstCtrl;//Panel type 

extern VControl UIMenuWndPhotoBurst_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndPhotoBurst_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoBurst_Menu_STRID_CAP_SINGLE,
UIMenuWndPhotoBurst_Menu_STRID_CAP_BURST_3,
UIMenuWndPhotoBurst_Menu_MAX
}UIMenuWndPhotoBurst_Menu_Setting;

//---------------------UIMenuWndPhotoBurstCtrl User Export---------------------------
#endif
