//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOQUICK_REVIEW_H
#define UIMENUWNDPHOTOQUICK_REVIEW_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoQuick_ReviewCtrl;//Panel type 

extern VControl UIMenuWndPhotoQuick_Review_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndPhotoQuick_Review_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoQuick_Review_Menu_STRID_OFF,
UIMenuWndPhotoQuick_Review_Menu_STRID_2SEC,
UIMenuWndPhotoQuick_Review_Menu_STRID_5SEC,
UIMenuWndPhotoQuick_Review_Menu_MAX
}UIMenuWndPhotoQuick_Review_Menu_Setting;

//---------------------UIMenuWndPhotoQuick_ReviewCtrl User Export---------------------------
#endif
