//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOISO_H
#define UIMENUWNDPHOTOISO_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoIsoCtrl;//Panel type 

extern VControl UIMenuWndPhotoIso_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndPhotoIso_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoIso_Menu_STRID_AUTO,
UIMenuWndPhotoIso_Menu_STRID_ISO100,
UIMenuWndPhotoIso_Menu_STRID_ISO200,
UIMenuWndPhotoIso_Menu_STRID_ISO400,
UIMenuWndPhotoIso_Menu_STRID_ISO800,
UIMenuWndPhotoIso_Menu_STRID_ISO1600,
UIMenuWndPhotoIso_Menu_MAX
}UIMenuWndPhotoIso_Menu_Setting;

//---------------------UIMenuWndPhotoIsoCtrl User Export---------------------------
#endif
