//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoIsoRes.c"
#include "UIMenuWndPhotoIso.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoIsoCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOISO_ERROR_MSG        1
#define _UIMENUWNDPHOTOISO_TRACE_MSG        0

#if (_UIMENUWNDPHOTOISO_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoIsoErrMsg(...)            debug_msg ("^R UIMenuWndPhotoIso: "__VA_ARGS__)
#else
#define UIMenuWndPhotoIsoErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOISO_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoIsoTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoIso: "__VA_ARGS__)
#else
#define UIMenuWndPhotoIsoTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoIsoCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoIsoCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoIsoCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoIsoCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoIsoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoIso)
CTRL_LIST_ITEM(UIMenuWndPhotoIso_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoIso_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoIsoCtrl Event---------------------------
INT32 UIMenuWndPhotoIso_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoIso_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoIso_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoIso_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoIso)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoIso_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoIso_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoIso_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoIso_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoIso_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_ISO))
	{
		case ISO_AUTO:  
			Data = 0;
			break;
		case ISO_100:  
			Data = 1;
			break;
		case ISO_200:  
			Data = 2;
			break;
		case ISO_400:  
			Data = 3;
			break;	
		case ISO_800:  
			Data = 4;
			break;
		case ISO_1600:  
			Data = 5;
			break;				
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoIso_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoIso_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPhotoIso_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoIso_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoIsoCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndPhotoIso_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoIso_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoIso_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoIso_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoIso_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoIso_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoIso_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoIso_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoIso_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoIso_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoIso_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoIso_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoIso_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoIso_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoIso_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = ISO_AUTO;
			break;

		case 1:
			uiSelItem = ISO_100;
			break;

		case 2: 
			uiSelItem = ISO_200;
			break;
		case 3: 
			uiSelItem = ISO_400;
			break;
		case 4: 
			uiSelItem = ISO_800;
			break;
		case 5: 
			uiSelItem = ISO_1600;
			break;			
		default:
			uiSelItem = ISO_AUTO;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_ISO, 1, uiSelItem);	
	 Ux_CloseWindow(&UIMenuWndPhotoIsoCtrl, 0);

    return NVTEVT_CONSUME;
}
