//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOTIMER_H
#define UIMENUWNDPHOTOTIMER_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoTimerCtrl;//Panel type 

extern VControl UIMenuWndPhotoTimer_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndPhotoTimer_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoTimer_Menu_STRID_OFF,
UIMenuWndPhotoTimer_Menu_STRID_CAP_TIMER2S,
UIMenuWndPhotoTimer_Menu_STRID_CAP_TIMER5S,
UIMenuWndPhotoTimer_Menu_STRID_CAP_TIMER10S,
UIMenuWndPhotoTimer_Menu_MAX
}UIMenuWndPhotoTimer_Menu_Setting;

//---------------------UIMenuWndPhotoTimerCtrl User Export---------------------------
#endif
