//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOANTI_SHAKING_H
#define UIMENUWNDPHOTOANTI_SHAKING_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoAnti_ShakingCtrl;//Panel type 

extern VControl UIMenuWndPhotoAnti_Shaking_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndPhotoAnti_Shaking_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoAnti_Shaking_Menu_STRID_OFF,
UIMenuWndPhotoAnti_Shaking_Menu_STRID_ON,
UIMenuWndPhotoAnti_Shaking_Menu_MAX
}UIMenuWndPhotoAnti_Shaking_Menu_Setting;

//---------------------UIMenuWndPhotoAnti_ShakingCtrl User Export---------------------------
#endif
