//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoQuick_ReviewRes.c"
#include "UIMenuWndPhotoQuick_Review.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoQuick_ReviewCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOQUICK_REVIEW_ERROR_MSG        1
#define _UIMENUWNDPHOTOQUICK_REVIEW_TRACE_MSG        0

#if (_UIMENUWNDPHOTOQUICK_REVIEW_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoQuick_ReviewErrMsg(...)            debug_msg ("^R UIMenuWndPhotoQuick_Review: "__VA_ARGS__)
#else
#define UIMenuWndPhotoQuick_ReviewErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOQUICK_REVIEW_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoQuick_ReviewTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoQuick_Review: "__VA_ARGS__)
#else
#define UIMenuWndPhotoQuick_ReviewTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoQuick_ReviewCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoQuick_ReviewCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoQuick_ReviewCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoQuick_ReviewCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoQuick_ReviewCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoQuick_Review)
CTRL_LIST_ITEM(UIMenuWndPhotoQuick_Review_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoQuick_Review_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoQuick_ReviewCtrl Event---------------------------
INT32 UIMenuWndPhotoQuick_Review_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuick_Review_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuick_Review_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuick_Review_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoQuick_Review)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoQuick_Review_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoQuick_Review_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoQuick_Review_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoQuick_Review_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoQuick_Review_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_QUICK_REVIEW))
	{
		case QUICK_REVIEW_0SEC:  
			Data = 0;
			break;
		case QUICK_REVIEW_2SEC:  
			Data = 1;
			break;	
		case QUICK_REVIEW_5SEC:  
			Data = 2;
			break;				
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoQuick_Review_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQuick_Review_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPhotoQuick_Review_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQuick_Review_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoQuick_ReviewCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}


//---------------------UIMenuWndPhotoQuick_Review_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoQuick_Review_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoQuick_Review_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoQuick_Review_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoQuick_Review_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoQuick_Review_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuick_Review_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuick_Review_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoQuick_Review_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoQuick_Review_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoQuick_Review_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoQuick_Review_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoQuick_Review_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQuick_Review_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQuick_Review_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = QUICK_REVIEW_0SEC;
			break;

		case 1:
			uiSelItem = QUICK_REVIEW_2SEC;
			break;		
		case 2:
			uiSelItem = QUICK_REVIEW_5SEC;
			break;				
		default:
			uiSelItem = QUICK_REVIEW_0SEC;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_PREVIEW, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndPhotoQuick_ReviewCtrl, 0);

    return NVTEVT_CONSUME;
}
