//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoCompressionRes.c"
#include "UIMenuWndPhotoCompression.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoCompressionCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOCOMPRESSION_ERROR_MSG        1
#define _UIMENUWNDPHOTOCOMPRESSION_TRACE_MSG        0

#if (_UIMENUWNDPHOTOCOMPRESSION_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoCompressionErrMsg(...)            debug_msg ("^R UIMenuWndPhotoCompression: "__VA_ARGS__)
#else
#define UIMenuWndPhotoCompressionErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOCOMPRESSION_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoCompressionTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoCompression: "__VA_ARGS__)
#else
#define UIMenuWndPhotoCompressionTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoCompressionCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoCompressionCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoCompressionCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoCompressionCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoCompressionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoCompression)
CTRL_LIST_ITEM(UIMenuWndPhotoCompression_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoCompression_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoCompressionCtrl Event---------------------------
INT32 UIMenuWndPhotoCompression_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoCompression_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoCompression_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoCompression_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoCompression)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoCompression_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoCompression_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoCompression_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoCompression_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoCompression_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_MOVIE_QUALITY))
	{
		case MOVIE_QUALITY_FINE:  
			Data = 0;
			break;
		case MOVIE_QUALITY_STANDARD:  
			Data = 1;
			break;	
		case MOVIE_QUALITY_ECONOMY:  
			Data = 2;
			break;				
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoCompression_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoCompression_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoCompression_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoCompression_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoCompressionCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoCompression_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoCompression_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoCompression_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoCompression_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoCompression_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoCompression_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoCompression_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoCompression_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoCompression_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoCompression_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoCompression_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoCompression_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoCompression_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoCompression_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoCompression_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = MOVIE_QUALITY_FINE;
			break;

		case 1:
			uiSelItem = MOVIE_QUALITY_STANDARD;
			break;

		case 2:
			uiSelItem = MOVIE_QUALITY_ECONOMY;
			break;
			
		default:
			uiSelItem = MOVIE_QUALITY_FINE;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_QUALITY, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndPhotoCompressionCtrl, 0);
    return NVTEVT_CONSUME;
}
