//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoDateStampRes.c"
#include "UIMenuWndPhotoDateStamp.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoDateStampCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTODATESTAMP_ERROR_MSG        1
#define _UIMENUWNDPHOTODATESTAMP_TRACE_MSG        0

#if (_UIMENUWNDPHOTODATESTAMP_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoDateStampErrMsg(...)            debug_msg ("^R UIMenuWndPhotoDateStamp: "__VA_ARGS__)
#else
#define UIMenuWndPhotoDateStampErrMsg(...)
#endif

#if (_UIMENUWNDPHOTODATESTAMP_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoDateStampTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoDateStamp: "__VA_ARGS__)
#else
#define UIMenuWndPhotoDateStampTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoDateStampCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoDateStampCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoDateStampCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoDateStampCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoDateStampCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoDateStamp)
CTRL_LIST_ITEM(UIMenuWndPhotoDateStamp_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoDateStamp_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoDateStampCtrl Event---------------------------
INT32 UIMenuWndPhotoDateStamp_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoDateStamp_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoDateStamp_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoDateStamp_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoDateStamp)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoDateStamp_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoDateStamp_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoDateStamp_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoDateStamp_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoDateStamp_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_DATE_STAMP))
	{
		case DATE_STAMP_OFF:  
			Data = 0;
			break;
		case DATE_STAMP_DATE:  
			Data = 1;
			break;	
		case DATE_STAMP_DATE_TIME:  
			Data = 2;
			break;				
		default:
			Data = 2;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoDateStamp_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoDateStamp_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPhotoDateStamp_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoDateStamp_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoDateStampCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndPhotoDateStamp_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoDateStamp_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoDateStamp_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoDateStamp_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoDateStamp_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoDateStamp_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoDateStamp_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoDateStamp_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoDateStamp_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoDateStamp_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoDateStamp_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoDateStamp_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoDateStamp_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoDateStamp_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoDateStamp_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = DATE_STAMP_OFF;
			break;

		case 1:
			uiSelItem = DATE_STAMP_DATE;
			break;		
		case 2:
			uiSelItem = DATE_STAMP_DATE_TIME;
			break;				
		default:
			uiSelItem = DATE_STAMP_DATE_TIME;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_DATE_PRINT, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndPhotoDateStampCtrl, 0);

    return NVTEVT_CONSUME;
}
