//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoSizeRes.c"
#include "UIMenuWndPhotoSize.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoSizeCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOSIZE_ERROR_MSG        1
#define _UIMENUWNDPHOTOSIZE_TRACE_MSG        0

#if (_UIMENUWNDPHOTOSIZE_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoSizeErrMsg(...)            debug_msg ("^R UIMenuWndPhotoSize: "__VA_ARGS__)
#else
#define UIMenuWndPhotoSizeErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOSIZE_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoSizeTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoSize: "__VA_ARGS__)
#else
#define UIMenuWndPhotoSizeTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoSizeCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoSizeCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoSizeCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoSizeCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoSizeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoSize)
CTRL_LIST_ITEM(UIMenuWndPhotoSize_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoSize_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoSizeCtrl Event---------------------------
INT32 UIMenuWndPhotoSize_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSize_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSize_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSize_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoSize)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoSize_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoSize_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoSize_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoSize_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoSize_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_PHOTO_SIZE))
	{
		case PHOTO_SIZE_12M:  
			Data = 0;
			break;
		case PHOTO_SIZE_10M:  
			Data = 1;
			break;
		case PHOTO_SIZE_8M:  
			Data = 2;
			break;
		case PHOTO_SIZE_5M:  
			Data = 3;
			break;	
		case PHOTO_SIZE_3M:  
			Data = 4;
			break;
		case PHOTO_SIZE_VGA:  
			Data = 5;
			break;				
		default:
			Data = 1;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoSize_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSize_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPhotoSize_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSize_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoSizeCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndPhotoSize_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoSize_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoSize_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoSize_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoSize_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoSize_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSize_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoSize_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoSize_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoSize_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoSize_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoSize_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoSize_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSize_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoSize_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = PHOTO_SIZE_12M;
			break;

		case 1:
			uiSelItem = PHOTO_SIZE_10M;
			break;

		case 2: 
			uiSelItem = PHOTO_SIZE_8M;
			break;
		case 3: 
			uiSelItem = PHOTO_SIZE_5M;
			break;
		case 4: 
			uiSelItem = PHOTO_SIZE_3M;
			break;
		case 5: 
			uiSelItem = PHOTO_SIZE_VGA;
			break;			
		default:
			uiSelItem = PHOTO_SIZE_10M;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_CAPTURE_SIZE, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndPhotoSizeCtrl, 0);
    return NVTEVT_CONSUME;
}
