//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoTimerRes.c"
#include "UIMenuWndPhotoTimer.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoTimerCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOTIMER_ERROR_MSG        1
#define _UIMENUWNDPHOTOTIMER_TRACE_MSG        0

#if (_UIMENUWNDPHOTOTIMER_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoTimerErrMsg(...)            debug_msg ("^R UIMenuWndPhotoTimer: "__VA_ARGS__)
#else
#define UIMenuWndPhotoTimerErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOTIMER_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoTimerTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoTimer: "__VA_ARGS__)
#else
#define UIMenuWndPhotoTimerTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoTimerCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoTimerCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoTimerCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoTimerCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoTimerCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoTimer)
CTRL_LIST_ITEM(UIMenuWndPhotoTimer_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoTimer_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoTimerCtrl Event---------------------------
INT32 UIMenuWndPhotoTimer_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoTimer_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoTimer_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoTimer_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoTimer)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoTimer_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoTimer_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoTimer_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoTimer_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoTimer_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_SELFTIMER))
	{
		case SELFTIMER_OFF:  
			Data = 0;
			break;
		case SELFTIMER_2SEC:  
			Data = 1;
			break;
		case SELFTIMER_5SEC:  
			Data = 2;
			break;
		case SELFTIMER_10SEC:  
			Data = 3;
			break;			
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoTimer_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoTimer_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPhotoTimer_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoTimer_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoTimerCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoTimer_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoTimer_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoTimer_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoTimer_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoTimer_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoTimer_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoTimer_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoTimer_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoTimer_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoTimer_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoTimer_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoTimer_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoTimer_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoTimer_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoTimer_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = SELFTIMER_OFF;
			break;

		case 1:
			uiSelItem = SELFTIMER_2SEC;
			break;

		case 2: 
			uiSelItem = SELFTIMER_5SEC;
			break;
		case 3: 
			uiSelItem = SELFTIMER_10SEC;
			break;
		default:
			uiSelItem = SELFTIMER_OFF;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_SELFTIMER, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndPhotoTimerCtrl, 0);
    return NVTEVT_CONSUME;
}
