//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoBurstRes.c"
#include "UIMenuWndPhotoBurst.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoBurstCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOBURST_ERROR_MSG        1
#define _UIMENUWNDPHOTOBURST_TRACE_MSG        0

#if (_UIMENUWNDPHOTOBURST_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoBurstErrMsg(...)            debug_msg ("^R UIMenuWndPhotoBurst: "__VA_ARGS__)
#else
#define UIMenuWndPhotoBurstErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOBURST_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoBurstTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoBurst: "__VA_ARGS__)
#else
#define UIMenuWndPhotoBurstTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoBurstCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoBurstCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoBurstCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoBurstCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoBurstCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoBurst)
CTRL_LIST_ITEM(UIMenuWndPhotoBurst_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoBurst_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoBurstCtrl Event---------------------------
INT32 UIMenuWndPhotoBurst_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoBurst_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoBurst_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoBurst_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoBurst)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoBurst_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoBurst_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoBurst_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoBurst_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoBurst_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_CONTINUE_SHOT))
	{
		case CONTINUE_SHOT_OFF:  
			Data = 0;
			break;
		case CONTINUE_SHOT_BURST_3:  
			Data = 1;
			break;		
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoBurst_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoBurst_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoBurst_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoBurst_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoBurstCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoBurst_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoBurst_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoBurst_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoBurst_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoBurst_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoBurst_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoBurst_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoBurst_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoBurst_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoBurst_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoBurst_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoBurst_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoBurst_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoBurst_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoBurst_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = CONTINUE_SHOT_OFF;
			break;

		case 1:
			uiSelItem = CONTINUE_SHOT_BURST_3;
			break;

		default:
			uiSelItem = CONTINUE_SHOT_OFF;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_CONTSHOT, 1, uiSelItem);	
    Ux_CloseWindow(&UIMenuWndPhotoBurstCtrl, 0);
    return NVTEVT_CONSUME;
}
