//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoAnti_ShakingRes.c"
#include "UIMenuWndPhotoAnti_Shaking.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPhotoAnti_ShakingCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOANTI_SHAKING_ERROR_MSG        1
#define _UIMENUWNDPHOTOANTI_SHAKING_TRACE_MSG        0

#if (_UIMENUWNDPHOTOANTI_SHAKING_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoAnti_ShakingErrMsg(...)            debug_msg ("^R UIMenuWndPhotoAnti_Shaking: "__VA_ARGS__)
#else
#define UIMenuWndPhotoAnti_ShakingErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOANTI_SHAKING_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoAnti_ShakingTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoAnti_Shaking: "__VA_ARGS__)
#else
#define UIMenuWndPhotoAnti_ShakingTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoAnti_ShakingCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoAnti_ShakingCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoAnti_ShakingCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoAnti_ShakingCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoAnti_ShakingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoAnti_Shaking)
CTRL_LIST_ITEM(UIMenuWndPhotoAnti_Shaking_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPhotoAnti_Shaking_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoAnti_ShakingCtrl Event---------------------------
INT32 UIMenuWndPhotoAnti_Shaking_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoAnti_Shaking_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoAnti_Shaking_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoAnti_Shaking_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoAnti_Shaking)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoAnti_Shaking_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoAnti_Shaking_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPhotoAnti_Shaking_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPhotoAnti_Shaking_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoAnti_Shaking_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_ANTISHAKE))
	{
		case ANTISHAKE_OFF:  
			Data = 0;
			break;
		case ANTISHAKE_ON:  
			Data = 1;
			break;	
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPhotoAnti_Shaking_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoAnti_Shaking_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPhotoAnti_Shaking_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoAnti_Shaking_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPhotoAnti_ShakingCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndPhotoAnti_Shaking_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoAnti_Shaking_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoAnti_Shaking_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoAnti_Shaking_BGMenu)
EVENT_END

//----------------------UIMenuWndPhotoAnti_Shaking_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoAnti_Shaking_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoAnti_Shaking_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoAnti_Shaking_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoAnti_Shaking_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoAnti_Shaking_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoAnti_Shaking_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoAnti_Shaking_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoAnti_Shaking_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoAnti_Shaking_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoAnti_Shaking_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = ANTISHAKE_OFF;
			break;

		case 1:
			uiSelItem = ANTISHAKE_ON;
			break;		
		default:
			uiSelItem = ANTISHAKE_OFF;
			break;
			
	}
       Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_ANTISHAKING, 1, uiSelItem);	
    Ux_CloseWindow(&UIMenuWndPhotoAnti_ShakingCtrl, 0);
    return NVTEVT_CONSUME;
}
