//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOSIZE_H
#define UIMENUWNDPHOTOSIZE_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoSizeCtrl;//Panel type 

extern VControl UIMenuWndPhotoSize_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndPhotoSize_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoSize_Menu_STRID_12MWXH,
UIMenuWndPhotoSize_Menu_STRID_10MWXH,
UIMenuWndPhotoSize_Menu_STRID_8MWXH,
UIMenuWndPhotoSize_Menu_STRID_5MWXH,
UIMenuWndPhotoSize_Menu_STRID_3MWXH,
UIMenuWndPhotoSize_Menu_STRID_VGAWXH,
UIMenuWndPhotoSize_Menu_MAX
}UIMenuWndPhotoSize_Menu_Setting;

//---------------------UIMenuWndPhotoSizeCtrl User Export---------------------------
#endif
