//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDDISPINFO_H
#define UIFLOWWNDDISPINFO_H

#include "UIFramework.h"

extern VControl UIFlowWndDispInfoCtrl;//Panel type 

extern VControl UIFlowWndDispInfo_QRCodeCtrl;//Panel type 
#endif
