//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDDISPINFORES_H
#define UIFLOWWNDDISPINFORES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Skin1Rect,0,0,319,239,0,0,2,2,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_ITEM_RECT(CMD_Rectangle,Skin2Rect,0,0,319,239,0,0,2,2,0,0,0)
SHOW_MAP_BEGIN(Skin2)
SHOW_MAP_BODY(Skin2Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin2,0,0,319,239)

SHOW_MAP_BEGIN(UIFlowWndDispInfo_QRCode)
SHOW_MAP_BODY(Skin2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndDispInfo_QRCode)
DECLARE_CTRL_LIST(UIFlowWndDispInfo_QRCode)
CREATE_CTRL(UIFlowWndDispInfo_QRCode,UIFlowWndDispInfo_QRCode,CTRL_WND,NULL,0 ,0,0,319,239)
SHOW_MAP_BEGIN(UIFlowWndDispInfo)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndDispInfo)
DECLARE_CTRL_LIST(UIFlowWndDispInfo)
CREATE_CTRL(UIFlowWndDispInfo,UIFlowWndDispInfo,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
