//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndDispInfoRes.c"
#include "UIFlowWndDispInfo.h"
#include "UIDisplay.h"
#include "QR_Encode.h"
#include "WiFiIpcAPI.h"
#include "UIInfo.h"
#include "UICfgDefault.h"
UINT32 g_QRWidth;
unsigned char g_QRBuf[MAX_BITDATA];
extern char gMacAddr[6];

//---------------------UIFlowWndDispInfoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndDispInfo)
CTRL_LIST_ITEM(UIFlowWndDispInfo_QRCode)
CTRL_LIST_END

//----------------------UIFlowWndDispInfoCtrl Event---------------------------
INT32 UIFlowWndDispInfo_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndDispInfo_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndDispInfo)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndDispInfo_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndDispInfo_OnClose)
EVENT_END

INT32 UIFlowWndDispInfo_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	{
		  UINT32 result =0;
		  Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
		  
		  result = WiFiIpc_init_wlan0_netdev(0); 
		  debug_msg("Liwk ---- Wifi Result :%d \r\n", result);
		  if (WiFiIpc_get_wlan0_efuse_mac(gMacAddr) < 0)
		  {
			 debug_msg("Liwk --- GetMac Fail!!!\r\n");
		  }
		  else
		  {
			 /* Generate QRCode */
			 //#NT#2016/12/27#KCHong -begin
			 //#NT#QRCode sample code
			 char WiFiInfo[50];
			 char sMacStr[32];
			 CHKPNT;
			 sprintf(sMacStr,"%02x%02x%02x%02x%02x%02x",gMacAddr[0],gMacAddr[1],gMacAddr[2],gMacAddr[3], gMacAddr[4], gMacAddr[5]);//ssid
			 snprintf(WiFiInfo, 50, "%s", sMacStr);
			 g_QRWidth = QRCode_Encode(WiFiInfo, g_QRBuf, sizeof(g_QRBuf));
			 debug_msg("QRCode width = %d mac:%s\r\n", g_QRWidth, sMacStr);
			 //#NT#2016/12/27#KCHong -end
		}
	}

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndDispInfo_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIFlowWndDispInfo_QRCodeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndDispInfo_QRCode)
CTRL_LIST_END

//----------------------UIFlowWndDispInfo_QRCodeCtrl Event---------------------------
INT32 UIFlowWndDispInfo_QRCode_OnRedraw(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndDispInfo_QRCode)
EVENT_ITEM(NVTEVT_REDRAW,UIFlowWndDispInfo_QRCode_OnRedraw)
EVENT_END

void _DrawQRCode(UIScreen ScreenObj, URECT QRBase, UINT32 Margin, unsigned char *QRBuf, UINT32 QRWidth)
{
	UPOINT Current;
	UINT32 i, j;
	UINT32 ByteIdx, BitIdx;

	if (QRWidth == 0)
		return;


	// Draw background
	GxGfx_SetShapeColor(CLRID_IDX_WHITE, CLRID_IDX_WHITE, NULL);
	GxGfx_FillRect(((DC**)ScreenObj)[GxGfx_OSD], QRBase.x, QRBase.y, QRBase.x+(QRWidth+Margin*2)*QRBase.w, QRBase.y + (QRWidth+Margin*2)*QRBase.h);
	Current.x = QRBase.x+Margin*QRBase.w;
	Current.y = QRBase.y+Margin*QRBase.h;

	// Draw qrcode
	GxGfx_SetShapeColor(CLRID_IDX_BLACK, CLRID_IDX_BLACK, NULL);
	for (i = 0; i < QRWidth; i++) {
		for (j = 0; j < QRWidth; j++) {
			ByteIdx = (i*QRWidth+j)/8;
			BitIdx = (i*QRWidth+j)%8;
			if (QRBuf[ByteIdx] & (0x80 >> BitIdx)) {
				GxGfx_FillRect(((DC**)ScreenObj)[GxGfx_OSD], Current.x, Current.y, Current.x+QRBase.w, Current.y+QRBase.h);
			}
			Current.x += QRBase.w;
		}
		Current.x = QRBase.x+Margin * QRBase.w;
		Current.y = QRBase.y+(Margin+i+1)*QRBase.h;
	}
}

void _ShowOSDString(UIScreen ScreenObj,CHAR *pString, UINT16 uiX, UINT16 uiY, UINT16 uiColor)
{
    #if 1
    GxGfx_SetTextColor(uiColor, _OSD_INDEX_GRAY, 0);
    GxGfx_Text(((DC**)ScreenObj)[GxGfx_OSD], uiX, uiY, pString);
    #else
    debug_err(("SenFP_ShowOSDString is empty function\r\n"));
    #endif
}

extern UIMenuStoreInfo  currentInfo;
extern char gSSID[NVT_WSC_MAX_SSID_LEN];
extern char gPASSPHRASE[NVT_MAX_WEP_KEY_LEN];

INT32 UIFlowWndDispInfo_QRCode_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIScreen ScreenObj = *paramArray;
	URECT QRBase = {0, 5, 4, 4};
	UINT32 QRMargin = 2;
	BOOL bReadMenuInfo;
	char pString[128];
	
    Ux_DefaultEvent(pCtrl, NVTEVT_REDRAW, paramNum, paramArray);
	if(1)
	{
		_DrawQRCode(ScreenObj, QRBase, QRMargin, (unsigned char *)g_QRBuf, g_QRWidth);
        if(Load_MenuInfoForDisp())
        {
              memset(&pString[0], 0, 128);
             sprintf(pString, "VER: %s", currentInfo.strSoftwareVer);	    
             _ShowOSDString(ScreenObj,pString, 10, 120, 4);
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "MAC:");
             _ShowOSDString(ScreenObj, pString, 120,35, 1);
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "%02x%02x%02x%02x%02x%02x",gMacAddr[0], gMacAddr[1],gMacAddr[2], gMacAddr[3],gMacAddr[4], gMacAddr[5]);
             _ShowOSDString(ScreenObj, pString, 120,60, 1);
             
             if(!strcmp(UI_GetSNInfo(), DEFAULT_SN))
             {
                memset(&pString[0], 0, 128);
                sprintf(pString, "UID: Not Written Error!!!");	    
                _ShowOSDString(ScreenObj, pString, 10, 140, 3);
             }else{
                memset(&pString[0], 0, 128);
                sprintf(pString, "UID: %s", UI_GetSNInfo());
                _ShowOSDString(ScreenObj, pString, 10,140, 4);
             }
             
             if(currentInfo.strSSID[0] == 0)
             {
                #if (MAC_APPEN_SSID==ENABLE)
                sprintf(currentInfo.strSSID,"CAR-DVR-%02x%02x",gMacAddr[4], gMacAddr[5]);
                #else
                sprintf(currentInfo.strSSID,"%s",gSSID);
                #endif
                sprintf(currentInfo.strPASSPHRASE,"%s",gPASSPHRASE);
             }
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "SSID:%s",currentInfo.strSSID);
             _ShowOSDString(ScreenObj, pString, 10,160, 1);
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "PSW:%s",currentInfo.strPASSPHRASE);
             _ShowOSDString(ScreenObj, pString, 10,180, 1);	
             
             if(1)
             {
                memset(&pString[0], 0, 128);
                sprintf(pString, "%s %s",__DATE__, __TIME__);
                _ShowOSDString(ScreenObj, pString, 10,200, 1);
             }  
        }
	}

    return NVTEVT_CONSUME;
}

