//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupMovieDetStampRes.c"
#include "UIMenuWndSetupMovieDetStamp.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupMovieDetStampCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPMOVIEDETSTAMP_ERROR_MSG        1
#define _UIMENUWNDSETUPMOVIEDETSTAMP_TRACE_MSG        0

#if (_UIMENUWNDSETUPMOVIEDETSTAMP_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupMovieDetStampErrMsg(...)            debug_msg ("^R UIMenuWndSetupMovieDetStamp: "__VA_ARGS__)
#else
#define UIMenuWndSetupMovieDetStampErrMsg(...)
#endif

#if (_UIMENUWNDSETUPMOVIEDETSTAMP_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupMovieDetStampTraceMsg(...)          debug_msg ("^B UIMenuWndSetupMovieDetStamp: "__VA_ARGS__)
#else
#define UIMenuWndSetupMovieDetStampTraceMsg(...)
#endif

//---------------------UIMenuWndSetupMovieDetStampCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupMovieDetStampCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupMovieDetStampCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupMovieDetStampCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupMovieDetStampCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupMovieDetStamp)
CTRL_LIST_ITEM(UIMenuWndSetupMovieDetStamp_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupMovieDetStamp_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupMovieDetStampCtrl Event---------------------------
INT32 UIMenuWndSetupMovieDetStamp_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieDetStamp_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieDetStamp_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieDetStamp_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupMovieDetStamp)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupMovieDetStamp_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupMovieDetStamp_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupMovieDetStamp_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupMovieDetStamp_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupMovieDetStamp_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_MOVIE_DATEIMPRINT))
	{
		case MOVIE_DATEIMPRINT_OFF:  
			Data = 0;
			break;
		case MOVIE_DATEIMPRINT_ON:  
			Data = 1;
			break;
		default:
			Data = 1;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupMovieDetStamp_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieDetStamp_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupMovieDetStamp_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieDetStamp_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupMovieDetStampCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupMovieDetStamp_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupMovieDetStamp_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupMovieDetStamp_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupMovieDetStamp_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupMovieDetStamp_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupMovieDetStamp_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieDetStamp_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieDetStamp_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupMovieDetStamp_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupMovieDetStamp_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupMovieDetStamp_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupMovieDetStamp_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupMovieDetStamp_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieDetStamp_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieDetStamp_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = MOVIE_DATEIMPRINT_OFF;
			break;

		case 1:
			uiSelItem = MOVIE_DATEIMPRINT_ON;
			break;
		default:
			uiSelItem = MOVIE_DATEIMPRINT_ON;
			break;
	}
	UI_SetData(FL_MOVIE_DATEIMPRINT_MENU, uiSelItem);
	if(UI_GetData(FL_MOVIE_DATEIMPRINT_MENU) != UI_GetData(FL_MOVIE_DATEIMPRINT))
	{
		Ux_SendEvent(&CustomMovieObjCtrl,	NVTEVT_EXE_MOVIE_DATE_IMPRINT, 1,  uiSelItem);
	}
	Ux_CloseWindow(&UIMenuWndSetupMovieDetStampCtrl, 0);    	
    return NVTEVT_CONSUME;
}
