//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPTIMELAPSE_H
#define UIMENUWNDSETUPTIMELAPSE_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupTimeLapseCtrl;//Panel type 

extern VControl UIMenuWndSetupTimeLapse_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupTimeLapse_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupTimeLapse_Menu_STRID_OFF,
UIMenuWndSetupTimeLapse_Menu_STRID_TIMELAPSE_12H,
UIMenuWndSetupTimeLapse_Menu_STRID_TIMELAPSE_24H,
UIMenuWndSetupTimeLapse_Menu_STRID_TIMELAPSE_48H,
UIMenuWndSetupTimeLapse_Menu_MAX
}UIMenuWndSetupTimeLapse_Menu_Setting;

#endif
