//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPLANGUAGE_H
#define UIMENUWNDSETUPLANGUAGE_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupLanguageCtrl;//Panel type 

extern VControl UIMenuWndSetupLanguage_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupLanguage_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupLanguage_Menu_STRID_LANG_EN,
UIMenuWndSetupLanguage_Menu_STRID_LANG_SC,
UIMenuWndSetupLanguage_Menu_MAX
}UIMenuWndSetupLanguage_Menu_Setting;

//---------------------UIMenuWndSetupLanguageCtrl User Export---------------------------
#endif
