//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupLanguageRes.c"
#include "UIMenuWndSetupLanguage.h"
#include "PrjCfg.h"
#include "UIFlow.h"
//---------------------UIMenuWndSetupLanguageCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPLANGUAGE_ERROR_MSG        1
#define _UIMENUWNDSETUPLANGUAGE_TRACE_MSG        0

#if (_UIMENUWNDSETUPLANGUAGE_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupLanguageErrMsg(...)            debug_msg ("^R UIMenuWndSetupLanguage: "__VA_ARGS__)
#else
#define UIMenuWndSetupLanguageErrMsg(...)
#endif

#if (_UIMENUWNDSETUPLANGUAGE_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupLanguageTraceMsg(...)          debug_msg ("^B UIMenuWndSetupLanguage: "__VA_ARGS__)
#else
#define UIMenuWndSetupLanguageTraceMsg(...)
#endif

//---------------------UIMenuWndSetupLanguageCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupLanguageCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupLanguageCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupLanguageCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupLanguageCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLanguage)
CTRL_LIST_ITEM(UIMenuWndSetupLanguage_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupLanguage_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupLanguageCtrl Event---------------------------
INT32 UIMenuWndSetupLanguage_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLanguage)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupLanguage_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupLanguage_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupLanguage_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupLanguage_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupLanguage_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_LANGUAGE))
	{
	#if 0
		case LANG_EN:  
			Data = 0;
			break;
		case LANG_FR:  
			Data = 1;
			break;
		case LANG_ES:  
			Data = 2;
			break;
		case LANG_PO:  
			Data = 3;
			break;
		case LANG_DE:  
			Data = 4;
			break;	
		case LANG_IT:  
			Data = 5;
			break;
		case LANG_SC:  
			Data = 6;
			break;
		case LANG_TC:  
			Data = 7;
			break;
		case LANG_RU:  
			Data = 8;
			break;
		case LANG_JP:  
			Data = 9;
			break;	
		#else
		case LANG_EN:  
			Data = 0;
			break;
		case LANG_SC:  
			Data = 1;
			break;
		#endif
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupLanguage_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupLanguage_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupLanguageCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupLanguage_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLanguage_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupLanguage_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupLanguage_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupLanguage_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupLanguage_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLanguage_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupLanguage_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupLanguage_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupLanguage_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupLanguage_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	#if 0
		case 0: 
			uiSelItem = LANG_EN;
			break;

		case 1:
			uiSelItem = LANG_FR;
			break;
		case 2:
			uiSelItem = LANG_ES;
			break;
		case 3:
			uiSelItem = LANG_PO;
			break;
		case 4:
			uiSelItem = LANG_DE;
			break;
		case 5: 
			uiSelItem = LANG_IT;
			break;

		case 6:
			uiSelItem = LANG_SC;
			break;
		case 7:
			uiSelItem = LANG_TC;
			break;
		case 8:
			uiSelItem = LANG_RU;
			break;
		case 9:
			uiSelItem = LANG_JP;
			break;
		#else
		case 0: 
			uiSelItem = LANG_EN;
			break;

		case 1:
			uiSelItem = LANG_SC;
			break;
		#endif
					
		default:
			uiSelItem = LANG_EN;
			break;
			
	}
      Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_LANGUAGE, 1, uiSelItem);	
   Ux_CloseWindow(&UIMenuWndSetupLanguageCtrl, 0);
    return NVTEVT_CONSUME;
}
