//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPLOWBATTERYPRO_H
#define UIMENUWNDSETUPLOWBATTERYPRO_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupLowBatteryProCtrl;//Panel type 

extern VControl UIMenuWndSetupLowBatteryPro_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupLowBatteryPro_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupLowBatteryPro_Menu_STRID_LOW,
UIMenuWndSetupLowBatteryPro_Menu_STRID_MED,
UIMenuWndSetupLowBatteryPro_Menu_STRID_HIGH,
UIMenuWndSetupLowBatteryPro_Menu_MAX
}UIMenuWndSetupLowBatteryPro_Menu_Setting;

#endif
