//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupGsensorRes.c"
#include "UIMenuWndSetupGsensor.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupGsensorCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPGSENSOR_ERROR_MSG        1
#define _UIMENUWNDSETUPGSENSOR_TRACE_MSG        0

#if (_UIMENUWNDSETUPGSENSOR_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupGsensorErrMsg(...)            debug_msg ("^R UIMenuWndSetupGsensor: "__VA_ARGS__)
#else
#define UIMenuWndSetupGsensorErrMsg(...)
#endif

#if (_UIMENUWNDSETUPGSENSOR_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupGsensorTraceMsg(...)          debug_msg ("^B UIMenuWndSetupGsensor: "__VA_ARGS__)
#else
#define UIMenuWndSetupGsensorTraceMsg(...)
#endif

//---------------------UIMenuWndSetupGsensorCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupGsensorCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupGsensorCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupGsensorCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupGsensorCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupGsensor)
CTRL_LIST_ITEM(UIMenuWndSetupGsensor_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupGsensor_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupGsensorCtrl Event---------------------------
INT32 UIMenuWndSetupGsensor_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGsensor_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGsensor_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGsensor_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupGsensor)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupGsensor_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupGsensor_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupGsensor_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupGsensor_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupGsensor_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_GSENSOR))
	{
		case GSENSOR_OFF:  
			Data = 0;
			break;
		case GSENSOR_LOW:  
			Data = 1;
			break;
		case GSENSOR_MED:  
			Data = 2;
			break;
		case GSENSOR_HIGH:  
			Data = 3;
			break;			
		default:
			Data = 2;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupGsensor_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGsensor_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupGsensor_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGsensor_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupGsensorCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupGsensor_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupGsensor_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupGsensor_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGsensor_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupGsensor_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupGsensor_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGsensor_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGsensor_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupGsensor_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupGsensor_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupGsensor_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupGsensor_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupGsensor_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGsensor_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGsensor_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = GSENSOR_OFF;
			break;

		case 1:
			uiSelItem = GSENSOR_LOW;
			break;

		case 2: 
			uiSelItem = GSENSOR_MED;
			break;
		case 3: 
			uiSelItem = GSENSOR_HIGH;
			break;
		default:
			uiSelItem = GSENSOR_MED;
			break;
			
	}
	Ux_SendEvent(&CustomMovieObjCtrl,   NVTEVT_EXE_GSENSOR, 1,  uiSelItem);
		Ux_CloseWindow(&UIMenuWndSetupGsensorCtrl, 0);

    return NVTEVT_CONSUME;
}
