//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupFrequencyRes.c"
#include "UIMenuWndSetupFrequency.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupFrequencyCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPFREQUENCY_ERROR_MSG        1
#define _UIMENUWNDSETUPFREQUENCY_TRACE_MSG        0

#if (_UIMENUWNDSETUPFREQUENCY_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupFrequencyErrMsg(...)            debug_msg ("^R UIMenuWndSetupFrequency: "__VA_ARGS__)
#else
#define UIMenuWndSetupFrequencyErrMsg(...)
#endif

#if (_UIMENUWNDSETUPFREQUENCY_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupFrequencyTraceMsg(...)          debug_msg ("^B UIMenuWndSetupFrequency: "__VA_ARGS__)
#else
#define UIMenuWndSetupFrequencyTraceMsg(...)
#endif

//---------------------UIMenuWndSetupFrequencyCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupFrequencyCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupFrequencyCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupFrequencyCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupFrequencyCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupFrequency)
CTRL_LIST_ITEM(UIMenuWndSetupFrequency_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupFrequency_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupFrequencyCtrl Event---------------------------
INT32 UIMenuWndSetupFrequency_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFrequency_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFrequency_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFrequency_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFrequency)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupFrequency_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupFrequency_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupFrequency_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupFrequency_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupFrequency_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_FREQUENCY))
	{
		case FREQUENCY_50HZ:  
			Data = 0;
			break;
		case FREQUENCY_60HZ:  
			Data = 1;
			break;
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupFrequency_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFrequency_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupFrequency_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFrequency_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupFrequencyCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupFrequency_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupFrequency_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupFrequency_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFrequency_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupFrequency_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupFrequency_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFrequency_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFrequency_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFrequency_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupFrequency_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupFrequency_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupFrequency_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupFrequency_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFrequency_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFrequency_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = FREQUENCY_50HZ;
			break;

		case 1:
			uiSelItem = FREQUENCY_60HZ;
			break;
		default:
			uiSelItem = FREQUENCY_50HZ;
			break;
			
	}
      Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_FREQ, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndSetupFrequencyCtrl, 0);
    return NVTEVT_CONSUME;
}
