//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupParkingRes.c"
#include "UIMenuWndSetupParking.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupParkingCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPPARKING_ERROR_MSG        1
#define _UIMENUWNDSETUPPARKING_TRACE_MSG        0

#if (_UIMENUWNDSETUPPARKING_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupParkingErrMsg(...)            debug_msg ("^R UIMenuWndSetupParking: "__VA_ARGS__)
#else
#define UIMenuWndSetupParkingErrMsg(...)
#endif

#if (_UIMENUWNDSETUPPARKING_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupParkingTraceMsg(...)          debug_msg ("^B UIMenuWndSetupParking: "__VA_ARGS__)
#else
#define UIMenuWndSetupParkingTraceMsg(...)
#endif

//---------------------UIMenuWndSetupParkingCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupParkingCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupParkingCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupParkingCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupParkingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupParking)
CTRL_LIST_ITEM(UIMenuWndSetupParking_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupParking_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupParkingCtrl Event---------------------------
INT32 UIMenuWndSetupParking_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupParking_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupParking_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupParking_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupParking)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupParking_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupParking_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupParking_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupParking_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupParking_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_MOVIE_PARK))
	{
		case MOVIE_PARK_OFF:  
			Data = 0;
			break;
		case MOVIE_PARK_LOW:  
			Data = 1;
			break;
		case MOVIE_PARK_MED:  
			Data = 2;
			break;
		case MOVIE_PARK_HIGH:  
			Data = 3;
			break;			
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupParking_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupParking_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupParking_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupParkingCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupParking_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupParkingCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupParking_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupParking_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupParking_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupParking_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupParking_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupParking_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupParking_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupParking_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupParking_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupParking_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupParking_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupParking_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupParking_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupParking_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupParking_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = MOVIE_PARK_OFF;
			break;

		case 1:
			uiSelItem = MOVIE_PARK_LOW;
			break;

		case 2: 
			uiSelItem = MOVIE_PARK_MED;
			break;
		case 3: 
			uiSelItem = MOVIE_PARK_HIGH;
			break;
		default:
			uiSelItem = MOVIE_PARK_OFF;
			break;
			
	}
	Ux_SendEvent(&CustomMovieObjCtrl,   NVTEVT_EXE_MOVIE_PARK, 1,  uiSelItem);
	Ux_CloseWindow(&UIMenuWndSetupParkingCtrl, 0);
    return NVTEVT_CONSUME;
}
