//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupKeySoundRes.c"
#include "UIMenuWndSetupKeySound.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupKeySoundCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPKEYSOUND_ERROR_MSG        1
#define _UIMENUWNDSETUPKEYSOUND_TRACE_MSG        0

#if (_UIMENUWNDSETUPKEYSOUND_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupKeySoundErrMsg(...)            debug_msg ("^R UIMenuWndSetupKeySound: "__VA_ARGS__)
#else
#define UIMenuWndSetupKeySoundErrMsg(...)
#endif

#if (_UIMENUWNDSETUPKEYSOUND_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupKeySoundTraceMsg(...)          debug_msg ("^B UIMenuWndSetupKeySound: "__VA_ARGS__)
#else
#define UIMenuWndSetupKeySoundTraceMsg(...)
#endif

//---------------------UIMenuWndSetupKeySoundCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupKeySoundCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupKeySoundCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupKeySoundCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupKeySoundCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupKeySound)
CTRL_LIST_ITEM(UIMenuWndSetupKeySound_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupKeySound_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupKeySoundCtrl Event---------------------------
INT32 UIMenuWndSetupKeySound_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupKeySound_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupKeySound_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupKeySound_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupKeySound)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupKeySound_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupKeySound_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupKeySound_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupKeySound_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupKeySound_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_BEEP))
	{
		case BEEP_OFF:  
			Data = 0;
			break;
		case BEEP_ON:  
			Data = 1;
			break;
		default:
			Data = 1;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupKeySound_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupKeySound_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupKeySound_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupKeySound_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupKeySoundCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupKeySound_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupKeySound_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupKeySound_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupKeySound_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupKeySound_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupKeySound_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupKeySound_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupKeySound_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupKeySound_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupKeySound_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupKeySound_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupKeySound_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupKeySound_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupKeySound_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupKeySound_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = BEEP_OFF;
			break;

		case 1:
			uiSelItem = BEEP_ON;
			break;
		default:
			uiSelItem = BEEP_ON;
			break;
			
	}
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_BEEPKEY, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndSetupKeySoundCtrl, 0);    
	
    return NVTEVT_CONSUME;
}
