//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupWifiRes.c"
#include "UIMenuWndSetupWifi.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupWifiCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPWIFI_ERROR_MSG        1
#define _UIMENUWNDSETUPWIFI_TRACE_MSG        0

#if (_UIMENUWNDSETUPWIFI_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupWifiErrMsg(...)            debug_msg ("^R UIMenuWndSetupWifi: "__VA_ARGS__)
#else
#define UIMenuWndSetupWifiErrMsg(...)
#endif

#if (_UIMENUWNDSETUPWIFI_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupWifiTraceMsg(...)          debug_msg ("^B UIMenuWndSetupWifi: "__VA_ARGS__)
#else
#define UIMenuWndSetupWifiTraceMsg(...)
#endif

UINT32 WifiOrMd = 0;//0:wifi set, 1:motiondet set

//---------------------UIMenuWndSetupWifiCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupWifiCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupWifiCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupWifiCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupWifiCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupWifi)
CTRL_LIST_ITEM(UIMenuWndSetupWifi_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupWifi_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupWifiCtrl Event---------------------------
INT32 UIMenuWndSetupWifi_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWifi_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWifi_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWifi_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupWifi)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupWifi_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupWifi_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupWifi_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupWifi_OnKeyMode)
EVENT_END



INT32 UIMenuWndSetupWifi_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{	
	UINT32 Data = 0;
	
	if(paramNum > 0)
	{
		WifiOrMd = paramArray[0];
		if(WifiOrMd == 0)
		{
			if (UI_GetData(FL_WIFI_LINK) != WIFI_LINK_OK)
				Data = 0;
			else
				Data = 1;
		}
		else if(WifiOrMd == 1)
		{
			if (UI_GetData(FL_MOVIE_MOTION_DET) == MOVIE_MOTIONDET_OFF)
				Data = 0;
			else
				Data = 1;
		}
	}
	else
	{
		if (UI_GetData(FL_WIFI_LINK) != WIFI_LINK_OK)
			Data = 0;
		else
			Data = 1;
	}
	
	UxMenu_SetData(&UIMenuWndSetupWifi_MenuCtrl, MNU_CURITM, Data);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWifi_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupWifi_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWifi_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupWifiCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupWifi_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupWifi_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupWifi_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWifi_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupWifi_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupWifi_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWifi_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWifi_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupWifi_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupWifi_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupWifi_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupWifi_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupWifi_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWifi_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWifi_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	if(WifiOrMd == 0)
	{
		switch(uiSelItem)
		{
			case 0: 
				uiSelItem = WIFI_OFF;
				break;
			case 1:
				uiSelItem = WIFI_ON;
				break;
			default:
				uiSelItem = WIFI_ON;
				break;
				
		}
		
	    if(uiSelItem == WIFI_ON)
	    {
	        if (UI_GetData(FL_WIFI_LINK) != WIFI_LINK_OK)
	        {
	            UI_SetData(FL_WIFI_LINK,WIFI_LINK_OK);
	            UI_SetData(FL_WIFI,WIFI_ON);
	            BKG_PostEvent(NVTEVT_BKW_WIFI_ON);
	        }
	    }
	    else
	    {
	        UI_SetData(FL_WIFI,WIFI_OFF);
	        if(UI_GetData(FL_WIFI_LINK)==WIFI_LINK_OK)
	        {
	            UI_SetData(FL_WIFI_LINK,WIFI_LINK_DISCONNECTING);
		 		Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP,0);
	        }
	    }
	}
	else if(WifiOrMd == 1)
	{
		switch(uiSelItem)
		{
			case 0: 
				uiSelItem = MOVIE_MOTIONDET_OFF;
				UI_SetData(FL_MOVIE_MOTION_DET_MENU, uiSelItem);
				break;
			case 1:
				uiSelItem = MOVIE_MOTIONDET_ON;
				UI_SetData(FL_MOVIE_MOTION_DET_MENU, uiSelItem);
				break;
			default:
				uiSelItem = MOVIE_MOTIONDET_OFF;
				UI_SetData(FL_MOVIE_MOTION_DET_MENU, uiSelItem);
				break;
				
		}
		Ux_SendEvent(&CustomMovieObjCtrl,	NVTEVT_EXE_MOTION_DET, 1,  uiSelItem);
		//UI_SetData(FL_MOVIE_MOTION_DET, uiSelItem);
	}
		
    Ux_CloseWindow(&UIMenuWndSetupWifiCtrl, 0);
    return NVTEVT_CONSUME;
}
