//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPPARKING_H
#define UIMENUWNDSETUPPARKING_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupParkingCtrl;//Panel type 

extern VControl UIMenuWndSetupParking_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupParking_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupParking_Menu_STRID_OFF,
UIMenuWndSetupParking_Menu_STRID_LOW,
UIMenuWndSetupParking_Menu_STRID_MED,
UIMenuWndSetupParking_Menu_STRID_HIGH,
UIMenuWndSetupParking_Menu_MAX
}UIMenuWndSetupParking_Menu_Setting;

//---------------------UIMenuWndSetupParkingCtrl User Export---------------------------
#endif
