//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPSCREENPRO_H
#define UIMENUWNDSETUPSCREENPRO_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupScreenProCtrl;//Panel type 

extern VControl UIMenuWndSetupScreenPro_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupScreenPro_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupScreenPro_Menu_STRID_OFF,
UIMenuWndSetupScreenPro_Menu_STRID_1MIN,
UIMenuWndSetupScreenPro_Menu_STRID_3MIN,
UIMenuWndSetupScreenPro_Menu_STRID_5MIN,
UIMenuWndSetupScreenPro_Menu_STRID_10MIN,
UIMenuWndSetupScreenPro_Menu_MAX
}UIMenuWndSetupScreenPro_Menu_Setting;

//---------------------UIMenuWndSetupScreenProCtrl User Export---------------------------
#endif
