//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupCycleRecRes.c"
#include "UIMenuWndSetupCycleRec.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupCycleRecCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPCYCLEREC_ERROR_MSG        1
#define _UIMENUWNDSETUPCYCLEREC_TRACE_MSG        0

#if (_UIMENUWNDSETUPCYCLEREC_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupCycleRecErrMsg(...)            debug_msg ("^R UIMenuWndSetupCycleRec: "__VA_ARGS__)
#else
#define UIMenuWndSetupCycleRecErrMsg(...)
#endif

#if (_UIMENUWNDSETUPCYCLEREC_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupCycleRecTraceMsg(...)          debug_msg ("^B UIMenuWndSetupCycleRec: "__VA_ARGS__)
#else
#define UIMenuWndSetupCycleRecTraceMsg(...)
#endif

//---------------------UIMenuWndSetupCycleRecCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupCycleRecCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupCycleRecCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupCycleRecCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupCycleRecCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCycleRec)
CTRL_LIST_ITEM(UIMenuWndSetupCycleRec_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupCycleRec_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupCycleRecCtrl Event---------------------------
INT32 UIMenuWndSetupCycleRec_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCycleRec_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCycleRec_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCycleRec_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupCycleRec)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupCycleRec_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupCycleRec_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupCycleRec_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupCycleRec_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupCycleRec_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_MOVIE_CYCLIC_REC))
	{
		case MOVIE_CYCLICREC_OFF:  
			Data = 0;
			break;
		case MOVIE_CYCLICREC_1MIN:  
			Data = 1;
			break;
		case MOVIE_CYCLICREC_3MIN:
			Data = 2;
			break;

		case MOVIE_CYCLICREC_5MIN:
			Data = 3;
			break;
		case MOVIE_CYCLICREC_10MIN:
			Data = 4;
		break;
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupCycleRec_MenuCtrl, MNU_CURITM, Data);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCycleRec_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupCycleRec_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCycleRec_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupCycleRecCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}



//---------------------UIMenuWndSetupCycleRec_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCycleRec_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupCycleRec_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCycleRec_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupCycleRec_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupCycleRec_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCycleRec_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCycleRec_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCycleRec_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupCycleRec_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupCycleRec_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupCycleRec_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupCycleRec_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCycleRec_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCycleRec_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = MOVIE_CYCLICREC_OFF;
			break;

		case 1:
			uiSelItem = MOVIE_CYCLICREC_1MIN;
			break;

		case 2: 
			uiSelItem = MOVIE_CYCLICREC_3MIN;
			break;
		case 3: 
			uiSelItem = MOVIE_CYCLICREC_5MIN;
			break;
		case 4: 
			uiSelItem = MOVIE_CYCLICREC_10MIN;
			break;

		default:
			uiSelItem = MOVIE_CYCLICREC_1MIN;
			break;
			
	}
	Ux_SendEvent(&CustomMovieObjCtrl,   NVTEVT_EXE_CYCLIC_REC, 1,  uiSelItem);
	Ux_CloseWindow(&UIMenuWndSetupCycleRecCtrl, 0);

    return NVTEVT_CONSUME;
}
