//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPCYCLEREC_H
#define UIMENUWNDSETUPCYCLEREC_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupCycleRecCtrl;//Panel type 

extern VControl UIMenuWndSetupCycleRec_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupCycleRec_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupCycleRec_Menu_STRID_OFF,
UIMenuWndSetupCycleRec_Menu_STRID_1MIN,
UIMenuWndSetupCycleRec_Menu_STRID_3MIN,
UIMenuWndSetupCycleRec_Menu_STRID_5MIN,
//UIMenuWndSetupCycleRec_Menu_STRID_10MIN,
UIMenuWndSetupCycleRec_Menu_MAX
}UIMenuWndSetupCycleRec_Menu_Setting;

//---------------------UIMenuWndSetupCycleRecCtrl User Export---------------------------
#endif
