//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupMovieAudioRes.c"
#include "UIMenuWndSetupMovieAudio.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupMovieAudioCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPMOVIEAUDIO_ERROR_MSG        1
#define _UIMENUWNDSETUPMOVIEAUDIO_TRACE_MSG        0

#if (_UIMENUWNDSETUPMOVIEAUDIO_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupMovieAudioErrMsg(...)            debug_msg ("^R UIMenuWndSetupMovieAudio: "__VA_ARGS__)
#else
#define UIMenuWndSetupMovieAudioErrMsg(...)
#endif

#if (_UIMENUWNDSETUPMOVIEAUDIO_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupMovieAudioTraceMsg(...)          debug_msg ("^B UIMenuWndSetupMovieAudio: "__VA_ARGS__)
#else
#define UIMenuWndSetupMovieAudioTraceMsg(...)
#endif

//---------------------UIMenuWndSetupMovieAudioCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupMovieAudioCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupMovieAudioCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupMovieAudioCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupMovieAudioCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupMovieAudio)
CTRL_LIST_ITEM(UIMenuWndSetupMovieAudio_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupMovieAudio_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupMovieAudioCtrl Event---------------------------
INT32 UIMenuWndSetupMovieAudio_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieAudio_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieAudio_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieAudio_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupMovieAudio)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupMovieAudio_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupMovieAudio_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupMovieAudio_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupMovieAudio_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupMovieAudio_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;
	switch(UI_GetData(FL_MOVIE_AUDIO))
	{
		case MOVIE_AUDIO_OFF:  
			Data = 0;
			break;
		case MOVIE_AUDIO_ON:  
			Data = 1;
			break;
		default:
			Data = 1;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupMovieAudio_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieAudio_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupMovieAudio_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieAudio_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupMovieAudioCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}


//---------------------UIMenuWndSetupMovieAudio_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupMovieAudio_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupMovieAudio_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupMovieAudio_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupMovieAudio_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupMovieAudio_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieAudio_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupMovieAudio_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupMovieAudio_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupMovieAudio_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupMovieAudio_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupMovieAudio_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupMovieAudio_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieAudio_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupMovieAudio_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = MOVIE_AUDIO_OFF;
			break;

		case 1:
			uiSelItem = MOVIE_AUDIO_ON;
			break;
		default:
			uiSelItem = MOVIE_AUDIO_ON;
			break;
			
	}
	Ux_SendEvent(&CustomMovieObjCtrl,   NVTEVT_EXE_MOVIE_AUDIO, 1,  uiSelItem);
	Ux_CloseWindow(&UIMenuWndSetupMovieAudioCtrl, 0);    
    return NVTEVT_CONSUME;
}
