//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupResolutionRes.c"
#include "UIMenuWndSetupResolution.h"
#include "PrjCfg.h"
#include "MenuCommonItem.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupResolutionCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPRESOLUTION_ERROR_MSG        1
#define _UIMENUWNDSETUPRESOLUTION_TRACE_MSG        0

#if (_UIMENUWNDSETUPRESOLUTION_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupResolutionErrMsg(...)            debug_msg ("^R UIMenuWndSetupResolution: "__VA_ARGS__)
#else
#define UIMenuWndSetupResolutionErrMsg(...)
#endif

#if (_UIMENUWNDSETUPRESOLUTION_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupResolutionTraceMsg(...)          debug_msg ("^B UIMenuWndSetupResolution: "__VA_ARGS__)
#else
#define UIMenuWndSetupResolutionTraceMsg(...)
#endif

//---------------------UIMenuWndSetupResolutionCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupResolutionCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupResolutionCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupResolutionCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupResolutionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupResolution)
CTRL_LIST_ITEM(UIMenuWndSetupResolution_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupResolution_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupResolutionCtrl Event---------------------------
INT32 UIMenuWndSetupResolution_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupResolution_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupResolution_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupResolution_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupResolution)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupResolution_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupResolution_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupResolution_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupResolution_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupResolution_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_MOVIE_SIZE))
	{
#if 0//(SENSOR_CAPS_COUNT >= 2)
		case MOVIE_SIZE_DUAL_2560x1440P30_1920x1080P30:  
			Data = 0;
			break;
		case MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30:  
			Data = 1;
			break;
		case MOVIE_SIZE_DUAL_1280x720P30_1920x1080P30:  
			Data = 2;
			break;	
		default:
			Data = 0;
			break;
#else
		case MOVIE_SIZE_FRONT_3840x2160P30:  
			Data = 0;
			break;
		case MOVIE_SIZE_FRONT_2560x1440P30:  
			Data = 1;
			break;
		case MOVIE_SIZE_FRONT_1920x1080P30:  
			Data = 2;
			break;	
		default:
			Data = 0;
			break;
#endif
	}
	UxMenu_SetData(&UIMenuWndSetupResolution_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupResolution_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupResolution_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupResolution_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupResolutionCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupResolution_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupResolution_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupResolution_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupResolution_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupResolution_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupResolution_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupResolution_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupResolution_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupResolution_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupResolution_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupResolution_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupResolution_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupResolution_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupResolution_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
extern void UIFlowWndMovie_Initparam(void);
INT32 UIMenuWndSetupResolution_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
#if 0//(SENSOR_CAPS_COUNT >= 2)
		case 0: 
			uiSelItem = MOVIE_SIZE_DUAL_2560x1440P30_1920x1080P30;
			break;

		case 1:
			uiSelItem = MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30;
			break;
		case 2:
			uiSelItem = MOVIE_SIZE_DUAL_1280x720P30_1920x1080P30;
			break;
			
		default:
			uiSelItem = MOVIE_SIZE_DUAL_2560x1440P30_1920x1080P30;
			break;
#else//imx415
		case 0: 
			uiSelItem = MOVIE_SIZE_FRONT_3840x2160P30;
			break;
		case 1:
			uiSelItem = MOVIE_SIZE_FRONT_2560x1440P30;
			break;
		case 2:
			uiSelItem = MOVIE_SIZE_FRONT_1920x1080P30;
			break;
			
		default:
			uiSelItem = MOVIE_SIZE_FRONT_3840x2160P30;
			break;
#endif
			
	}

	SysSetFlag(FL_MOVIE_SIZE, uiSelItem);
	SysSetFlag(FL_MOVIE_SIZE_MENU, uiSelItem);
	Ux_SendEvent(&CustomMovieObjCtrl,   NVTEVT_EXE_MOVIESIZE, 1, SysGetFlag(FL_MOVIE_SIZE));
    Ux_CloseWindow(&UIMenuWndSetupResolutionCtrl, 0);
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
    return NVTEVT_CONSUME;
}
