//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupGPSINFORes.c"
#include "UIMenuWndSetupGPSINFO.h"
#include "GPS.h"
#include "UIFlow.h"

#if(FACTORY_TEST_MODE)
#define GPS_INFOSHOW	1
#else
#define GPS_INFOSHOW	0
#endif

#if GPS_INFOSHOW
extern GSVINFO GSVInfo;
extern UINT32  SenNum;
#endif

//---------------------UIMenuWndSetupGPS_INFOCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupGPS_INFO)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFO_PanelTop)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFO_Panel_BG)
CTRL_LIST_END

//----------------------UIMenuWndSetupGPS_INFOCtrl Event---------------------------
INT32 UIMenuWndSetupGPS_INFO_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_INFO_OnTimer(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(UIMenuWndSetupGPS_INFO)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupGPS_INFO_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupGPS_INFO_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupGPS_INFO_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupGPS_INFO_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupGPS_INFO_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupGPS_INFO_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupGPS_INFO_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupGPS_INFO_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupGPS_INFO_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupGPS_INFO_OnKeyShutter2)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndSetupGPS_INFO_OnTimer)
EVENT_END

static  UINT32 g_uiGPS_OneSecTimerID = NULL_TIMER ;
static void UIMenuWndSetupGPS_IconDrawGPS(void);

INT32 UIMenuWndSetupGPS_INFO_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    CHKPNT; 
    if (g_uiGPS_OneSecTimerID == NULL_TIMER)
    {
        CHKPNT;
        g_uiGPS_OneSecTimerID = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
	
	Ux_PostEvent(NVTEVT_TIMER, 1, NVTEVT_1SEC_TIMER);	//early to record
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_uiGPS_OneSecTimerID != NULL_TIMER)
    {
        GxTimer_StopTimer(&g_uiGPS_OneSecTimerID);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_LEFT,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(& UIMenuWndSetupGPS_INFOCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(& UIMenuWndSetupGPS_INFOCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_INFO_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //static UINT32  cnt = 0;
    UINT32  uiEvent;
    uiEvent = paramNum ? paramArray[0] : 0;
    switch(uiEvent)
    {
    case NVTEVT_1SEC_TIMER:
        UIMenuWndSetupGPS_IconDrawGPS();
        break;
    default :
        break;
    }
	Ux_DefaultEvent(pCtrl, NVTEVT_TIMER, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
#if 1
static CHAR    SatNums_str[64] = {0};
static CHAR    lat_str[64] = {0};
static CHAR    long_str[64] = {0};
#endif
static void UIMenuWndSetupGPS_IconDrawGPS(void)
{
  	RMCINFO RMCInfo;
    GPSRec_GetRMCDate(&RMCInfo);
	
#if 1
	sprintf(SatNums_str,"%2d",GPSRec_GetGSVSatInView());
	//debug_msg("\r\n ^^^SatNums:%s\r\n",SatNums_str);
    sprintf(lat_str,"%.8f",RMCInfo.Latitude);
    sprintf(long_str,"%.8f",RMCInfo.Longitude);	
#endif
#if GPS_INFOSHOW
	//sprintf(SatNums_str,"%2d/%ddb,%2d/%ddb,%2d/%ddb,%2d/%ddb",GSVInfo.SAT01.SatNum,GSVInfo.SAT01.SNR,GSVInfo.SAT02.SatNum,GSVInfo.SAT02.SNR,GSVInfo.SAT03.SatNum,GSVInfo.SAT03.SNR,GSVInfo.SAT04.SatNum,GSVInfo.SAT04.SNR);
	//sprintf(lat_str,"%2d/%ddb,%2d/%ddb,%2d/%ddb,%2d/%ddb",GSVInfo.SAT05.SatNum,GSVInfo.SAT05.SNR,GSVInfo.SAT06.SatNum,GSVInfo.SAT06.SNR,GSVInfo.SAT07.SatNum,GSVInfo.SAT07.SNR,GSVInfo.SAT08.SatNum,GSVInfo.SAT08.SNR);
	//sprintf(long_str,"%2d/%ddb,%2d/%ddb,%2d/%ddb,%2d/%ddb",GSVInfo.SAT09.SatNum,GSVInfo.SAT09.SNR,GSVInfo.SAT10.SatNum,GSVInfo.SAT10.SNR,GSVInfo.SAT11.SatNum,GSVInfo.SAT11.SNR,GSVInfo.SAT12.SatNum,GSVInfo.SAT12.SNR);
	sprintf(SatNums_str,"%2d/%d,%2d/%d,%2d/%d,%2d/%d",GSVInfo.SAT01.SatNum,GSVInfo.SAT01.SNR,GSVInfo.SAT02.SatNum,GSVInfo.SAT02.SNR,GSVInfo.SAT03.SatNum,GSVInfo.SAT03.SNR,GSVInfo.SAT04.SatNum,GSVInfo.SAT04.SNR);
	sprintf(long_str,"%2d/%d,%2d/%d,%2d/%d,%2d/%d",GSVInfo.SAT05.SatNum,GSVInfo.SAT05.SNR,GSVInfo.SAT06.SatNum,GSVInfo.SAT06.SNR,GSVInfo.SAT07.SatNum,GSVInfo.SAT07.SNR,GSVInfo.SAT08.SatNum,GSVInfo.SAT08.SNR);
	sprintf(lat_str,"%2d/%d,%2d/%d,%2d/%d,%2d/%d",GSVInfo.SAT09.SatNum,GSVInfo.SAT09.SNR,GSVInfo.SAT10.SatNum,GSVInfo.SAT10.SNR,GSVInfo.SAT11.SatNum,GSVInfo.SAT11.SNR,GSVInfo.SAT12.SatNum,GSVInfo.SAT12.SNR);

#endif
    UxStatic_SetData(&UIMenuWndSetupGPS_INFOText_SatellitesValueCtrl,STATIC_VALUE,Txt_Pointer(SatNums_str));
    UxStatic_SetData(&UIMenuWndSetupGPS_INFOText_LongValueCtrl,STATIC_VALUE,Txt_Pointer(long_str));
    UxStatic_SetData(&UIMenuWndSetupGPS_INFOText_LATValueCtrl,STATIC_VALUE,Txt_Pointer(lat_str));
	
    UxCtrl_SetShow(&UIMenuWndSetupGPS_INFO_Panel_BGCtrl,TRUE);
	UxCtrl_SetShow(&UIMenuWndSetupGPS_INFOText_SatellitesValueCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndSetupGPS_INFOText_LongValueCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndSetupGPS_INFOText_LATValueCtrl,TRUE);
}

//---------------------UIMenuWndSetupGPS_INFO_PanelTopCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupGPS_INFO_PanelTop)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFO_StaticTxT_Title)
CTRL_LIST_END

//----------------------UIMenuWndSetupGPS_INFO_PanelTopCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFO_PanelTop)
EVENT_END

//----------------------UIMenuWndSetupGPS_INFO_StaticTxT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFO_StaticTxT_Title)
EVENT_END

//---------------------UIMenuWndSetupGPS_INFO_Panel_BGCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupGPS_INFO_Panel_BG)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFO_StaticTxT_SATELLITES)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFOText_SatellitesValue)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFO_StaticTxT_LONG)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFOText_LongValue)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFO_StaticTxT_LAT)
CTRL_LIST_ITEM(UIMenuWndSetupGPS_INFOText_LATValue)
CTRL_LIST_END

//----------------------UIMenuWndSetupGPS_INFO_Panel_BGCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFO_Panel_BG)
EVENT_END

//----------------------UIMenuWndSetupGPS_INFO_StaticTxT_SATELLITESCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFO_StaticTxT_SATELLITES)
EVENT_END

//----------------------UIMenuWndSetupGPS_INFOText_SatellitesValueCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFOText_SatellitesValue)
EVENT_END

//----------------------UIMenuWndSetupGPS_INFO_StaticTxT_LONGCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFO_StaticTxT_LONG)
EVENT_END

//----------------------UIMenuWndSetupGPS_INFOText_LongValueCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFOText_LongValue)
EVENT_END

//----------------------UIMenuWndSetupGPS_INFO_StaticTxT_LATCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFO_StaticTxT_LAT)
EVENT_END

//----------------------UIMenuWndSetupGPS_INFOText_LATValueCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupGPS_INFOText_LATValue)
EVENT_END

