//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupWDRRes.c"
#include "UIMenuWndSetupWDR.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupWDRCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPWDR_ERROR_MSG        1
#define _UIMENUWNDSETUPWDR_TRACE_MSG        0

#if (_UIMENUWNDSETUPWDR_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupWDRErrMsg(...)            debug_msg ("^R UIMenuWndSetupWDR: "__VA_ARGS__)
#else
#define UIMenuWndSetupWDRErrMsg(...)
#endif

#if (_UIMENUWNDSETUPWDR_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupWDRTraceMsg(...)          debug_msg ("^B UIMenuWndSetupWDR: "__VA_ARGS__)
#else
#define UIMenuWndSetupWDRTraceMsg(...)
#endif

//---------------------UIMenuWndSetupWDRCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupWDRCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupWDRCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupWDRCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupWDRCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupWDR)
CTRL_LIST_ITEM(UIMenuWndSetupWDR_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupWDR_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupWDRCtrl Event---------------------------
INT32 UIMenuWndSetupWDR_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWDR_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWDR_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWDR_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupWDR)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupWDR_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupWDR_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupWDR_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupWDR_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupWDR_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_MOVIE_WDR))
	{
		case MOVIE_WDR_OFF:  
			Data = 0;
			break;
		case MOVIE_WDR_ON:  
			Data = 1;
			break;
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupWDR_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWDR_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupWDR_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWDR_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupWDRCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}


//---------------------UIMenuWndSetupWDR_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupWDR_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupWDR_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWDR_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupWDR_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupWDR_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWDR_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWDR_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupWDR_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupWDR_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupWDR_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupWDR_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupWDR_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWDR_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWDR_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = MOVIE_WDR_OFF;
			break;

		case 1:
			uiSelItem = MOVIE_WDR_ON;
			break;
		default:
			uiSelItem = MOVIE_WDR_OFF;
			break;
			
	}
	Ux_SendEvent(&CustomMovieObjCtrl,   NVTEVT_EXE_MOVIE_WDR, 1,  uiSelItem);
	Ux_CloseWindow(&UIMenuWndSetupWDRCtrl, 0);    
	return NVTEVT_CONSUME;
}
