//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPGSENSOR_H
#define UIMENUWNDSETUPGSENSOR_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupGsensorCtrl;//Panel type 

extern VControl UIMenuWndSetupGsensor_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupGsensor_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupGsensor_Menu_STRID_OFF,
UIMenuWndSetupGsensor_Menu_STRID_LOW,
UIMenuWndSetupGsensor_Menu_STRID_MED,
UIMenuWndSetupGsensor_Menu_STRID_HIGH,
UIMenuWndSetupGsensor_Menu_MAX
}UIMenuWndSetupGsensor_Menu_Setting;

//---------------------UIMenuWndSetupGsensorCtrl User Export---------------------------
#endif
