//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupLowbatteryProRes.c"
#include "UIMenuWndSetupLowbatteryPro.h"
#include "PrjCfg.h"
#include "UIFlow.h"  

//---------------------UIMenuWndSetupLowBatteryProCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLowBatteryPro)
CTRL_LIST_ITEM(UIMenuWndSetupLowBatteryPro_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupLowBatteryPro_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupLowBatteryProCtrl Event---------------------------
INT32 UIMenuWndSetupLowBatteryPro_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLowBatteryPro_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLowBatteryPro_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLowBatteryPro_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLowBatteryPro)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupLowBatteryPro_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupLowBatteryPro_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupLowBatteryPro_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupLowBatteryPro_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupLowBatteryPro_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_LowBatteryLvl))
	{
		case LOWBATTERY_LVL_1:  
			Data = 0;
			break;
		case LOWBATTERY_LVL_2:  
			Data = 1;
			break;
		case LOWBATTERY_LVL_3:  
			Data = 2;
			break;
			
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupLowBatteryPro_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLowBatteryPro_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLowBatteryPro_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLowBatteryPro_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupLowBatteryProCtrl, 0);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupLowBatteryPro_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLowBatteryPro_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupLowBatteryPro_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupLowBatteryPro_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupLowBatteryPro_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupLowBatteryPro_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLowBatteryPro_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLowBatteryPro_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLowBatteryPro_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupLowBatteryPro_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupLowBatteryPro_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupLowBatteryPro_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupLowBatteryPro_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLowBatteryPro_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLowBatteryPro_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
		case 0: 
			uiSelItem = LOWBATTERY_LVL_1;
			break;

		case 1:
			uiSelItem = LOWBATTERY_LVL_2;
			break;
		case 2:
			uiSelItem = LOWBATTERY_LVL_3;
			break;
			
		default:
			uiSelItem = LOWBATTERY_LVL_1; 
			break;
			
	}
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_SETUP_LOWBATTERYLVL, 1, uiSelItem);
	Ux_CloseWindow(&UIMenuWndSetupLowBatteryProCtrl, 0);
    return NVTEVT_CONSUME;
}
