//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPKEYSOUND_H
#define UIMENUWNDSETUPKEYSOUND_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupKeySoundCtrl;//Panel type 

extern VControl UIMenuWndSetupKeySound_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupKeySound_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupKeySound_Menu_STRID_OFF,
UIMenuWndSetupKeySound_Menu_STRID_ON,
UIMenuWndSetupKeySound_Menu_MAX
}UIMenuWndSetupKeySound_Menu_Setting;

//---------------------UIMenuWndSetupKeySoundCtrl User Export---------------------------
#endif
