//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPGPSINFO_H
#define UIMENUWNDSETUPGPSINFO_H


#include "UIFramework.h"

extern VControl UIMenuWndSetupGPS_INFOCtrl;//Panel type 

extern VControl UIMenuWndSetupGPS_INFO_PanelTopCtrl;//Panel type 

extern VControl UIMenuWndSetupGPS_INFO_StaticTxT_TitleCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_INFO_Panel_BGCtrl;//Panel type 

extern VControl UIMenuWndSetupGPS_INFO_StaticTxT_SATELLITESCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_INFOText_SatellitesValueCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_INFO_StaticTxT_LONGCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_INFOText_LongValueCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_INFO_StaticTxT_LATCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_INFOText_LATValueCtrl;//Static type 

#endif
