//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPMOVIEDETSTAMP_H
#define UIMENUWNDSETUPMOVIEDETSTAMP_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupMovieDetStampCtrl;//Panel type 

extern VControl UIMenuWndSetupMovieDetStamp_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupMovieDetStamp_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupMovieDetStamp_Menu_STRID_OFF,
UIMenuWndSetupMovieDetStamp_Menu_STRID_ON,
UIMenuWndSetupMovieDetStamp_Menu_MAX
}UIMenuWndSetupMovieDetStamp_Menu_Setting;

//---------------------UIMenuWndSetupMovieDetStampCtrl User Export---------------------------
#endif
