//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPWDR_H
#define UIMENUWNDSETUPWDR_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupWDRCtrl;//Panel type 

extern VControl UIMenuWndSetupWDR_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupWDR_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupWDR_Menu_STRID_OFF,
UIMenuWndSetupWDR_Menu_STRID_ON,
UIMenuWndSetupWDR_Menu_MAX
}UIMenuWndSetupWDR_Menu_Setting;

//---------------------UIMenuWndSetupWDRCtrl User Export---------------------------
#endif
