//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupScreenProRes.c"
#include "UIMenuWndSetupScreenPro.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupScreenProCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPSCREENPRO_ERROR_MSG        1
#define _UIMENUWNDSETUPSCREENPRO_TRACE_MSG        0

#if (_UIMENUWNDSETUPSCREENPRO_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupScreenProErrMsg(...)            debug_msg ("^R UIMenuWndSetupScreenPro: "__VA_ARGS__)
#else
#define UIMenuWndSetupScreenProErrMsg(...)
#endif

#if (_UIMENUWNDSETUPSCREENPRO_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupScreenProTraceMsg(...)          debug_msg ("^B UIMenuWndSetupScreenPro: "__VA_ARGS__)
#else
#define UIMenuWndSetupScreenProTraceMsg(...)
#endif

//---------------------UIMenuWndSetupScreenProCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupScreenProCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupScreenProCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupScreenProCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupScreenProCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupScreenPro)
CTRL_LIST_ITEM(UIMenuWndSetupScreenPro_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupScreenPro_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupScreenProCtrl Event---------------------------
INT32 UIMenuWndSetupScreenPro_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupScreenPro_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupScreenPro_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupScreenPro_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupScreenPro)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupScreenPro_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupScreenPro_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupScreenPro_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupScreenPro_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupScreenPro_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_LCD_OFF))
	{
		case LCDOFF_ON:  
			Data = 0;
			break;
		case LCDOFF_1MIN:  
			Data = 1;
			break;
		case LCDOFF_3MIN:  
			Data = 2;
			break;
		case LCDOFF_5MIN:  
			Data = 3;
			break;
		case LCDOFF_10MIN:  
			Data = 4;
			break;			
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupScreenPro_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupScreenPro_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupScreenPro_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupScreenPro_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupScreenProCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupScreenPro_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupScreenPro_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupScreenPro_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupScreenPro_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupScreenPro_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupScreenPro_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupScreenPro_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupScreenPro_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupScreenPro_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupScreenPro_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupScreenPro_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupScreenPro_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupScreenPro_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupScreenPro_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupScreenPro_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = LCDOFF_ON;
			break;

		case 1:
			uiSelItem = LCDOFF_1MIN;
			break;
		case 2:
			uiSelItem = LCDOFF_3MIN;
			break;
		case 3:
			uiSelItem = LCDOFF_5MIN;
			break;
		case 4:
			uiSelItem = LCDOFF_10MIN;
			break;
			
		default:
			uiSelItem = LCDOFF_ON;
			break;
			
	}
      Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_LCDOFF, 1, uiSelItem);	
	Ux_CloseWindow(&UIMenuWndSetupScreenProCtrl, 0);
    return NVTEVT_CONSUME;
}
