//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPMOVIEAUDIO_H
#define UIMENUWNDSETUPMOVIEAUDIO_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupMovieAudioCtrl;//Panel type 

extern VControl UIMenuWndSetupMovieAudio_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupMovieAudio_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupMovieAudio_Menu_STRID_OFF,
UIMenuWndSetupMovieAudio_Menu_STRID_ON,
UIMenuWndSetupMovieAudio_Menu_MAX
}UIMenuWndSetupMovieAudio_Menu_Setting;

//---------------------UIMenuWndSetupMovieAudioCtrl User Export---------------------------
#endif
