//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPFREQUENCY_H
#define UIMENUWNDSETUPFREQUENCY_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupFrequencyCtrl;//Panel type 

extern VControl UIMenuWndSetupFrequency_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupFrequency_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupFrequency_Menu_STRID_50HZ,
UIMenuWndSetupFrequency_Menu_STRID_60HZ,
UIMenuWndSetupFrequency_Menu_MAX
}UIMenuWndSetupFrequency_Menu_Setting;

//---------------------UIMenuWndSetupFrequencyCtrl User Export---------------------------
#endif
