//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPWIFI_H
#define UIMENUWNDSETUPWIFI_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupWifiCtrl;//Panel type 

extern VControl UIMenuWndSetupWifi_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupWifi_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupWifi_Menu_STRID_OFF,
UIMenuWndSetupWifi_Menu_STRID_ON,
UIMenuWndSetupWifi_Menu_MAX
}UIMenuWndSetupWifi_Menu_Setting;

//---------------------UIMenuWndSetupWifiCtrl User Export---------------------------
#endif
