//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPRESOLUTION_H
#define UIMENUWNDSETUPRESOLUTION_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupResolutionCtrl;//Panel type 

extern VControl UIMenuWndSetupResolution_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndSetupResolution_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupResolution_Menu_STRID_2160P_1080P,
UIMenuWndSetupResolution_Menu_STRID_1440P_1080P,
UIMenuWndSetupResolution_Menu_STRID_1080P_1080P,
UIMenuWndSetupResolution_Menu_MAX
}UIMenuWndSetupResolution_Menu_Setting;

#endif
