//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupTimeLapseRes.c"
#include "UIMenuWndSetupTimeLapse.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndSetupTimeLapseCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupTimeLapse)
CTRL_LIST_ITEM(UIMenuWndSetupTimeLapse_BGMenu)
CTRL_LIST_ITEM(UIMenuWndSetupTimeLapse_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupTimeLapseCtrl Event---------------------------
INT32 UIMenuWndSetupTimeLapse_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupTimeLapse_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupTimeLapse_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupTimeLapse_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupTimeLapse)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupTimeLapse_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupTimeLapse_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupTimeLapse_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupTimeLapse_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupTimeLapse_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_movie_timelapse_set))
	{
		case MOVIE_TIMELAPSE_SET_OFF:  
			Data = 0;
			break;
		case MOVIE_TIMELAPSE_SET_12HOUR:  
			Data = 1;
			break;
		case MOVIE_TIMELAPSE_SET_24HOUR:  
			Data = 2;
			break;
		case MOVIE_TIMELAPSE_SET_48HOUR:  
			Data = 3;
			break;		
		default:
			Data = 0;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndSetupTimeLapse_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupTimeLapse_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupTimeLapse_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupTimeLapse_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupTimeLapseCtrl, 0);
	return NVTEVT_CONSUME;
}

//---------------------UIMenuWndSetupTimeLapse_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupTimeLapse_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndSetupTimeLapse_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupTimeLapse_BGMenu)
EVENT_END

//----------------------UIMenuWndSetupTimeLapse_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupTimeLapse_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupTimeLapse_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupTimeLapse_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupTimeLapse_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupTimeLapse_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupTimeLapse_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupTimeLapse_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupTimeLapse_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupTimeLapse_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupTimeLapse_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
		case 0: 
			uiSelItem = MOVIE_TIMELAPSE_SET_OFF;
			break;

		case 1:
			uiSelItem = MOVIE_TIMELAPSE_SET_12HOUR;
			break;
		case 2:
			uiSelItem = MOVIE_TIMELAPSE_SET_24HOUR;
			break;
		case 3:
			uiSelItem = MOVIE_TIMELAPSE_SET_48HOUR;
			break;
			
		default:
			uiSelItem = MOVIE_TIMELAPSE_SET_OFF;
			break;
			
	}
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_MOVIE_TIMELAPSESET, 1, uiSelItem);
	Ux_CloseWindow(&UIMenuWndSetupTimeLapseCtrl, 0);
    return NVTEVT_CONSUME;
}
