//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYVOLUME_H
#define UIMENUWNDPLAYVOLUME_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayVolumeCtrl;//Panel type 

extern VControl UIMenuWndPlayVolume_BGMenuCtrl;//Panel type 

extern VControl UIMenuWndPlayVolume_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayVolume_Menu_STRID_0,
UIMenuWndPlayVolume_Menu_STRID_3,
UIMenuWndPlayVolume_Menu_STRID_4,
UIMenuWndPlayVolume_Menu_STRID_5,
UIMenuWndPlayVolume_Menu_STRID_6,
UIMenuWndPlayVolume_Menu_STRID_7,
UIMenuWndPlayVolume_Menu_STRID_8,
UIMenuWndPlayVolume_Menu_STRID_9,
UIMenuWndPlayVolume_Menu_STRID_10,
UIMenuWndPlayVolume_Menu_MAX
}UIMenuWndPlayVolume_Menu_Setting;

//---------------------UIMenuWndPlayVolumeCtrl User Export---------------------------
#endif
