//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayProtectRes.c"
#include "UIMenuWndPlayProtect.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPlayProtectCtrl Debug Definition -----------------------------
#define _UIMENUWNDPLAYPROTECT_ERROR_MSG        1
#define _UIMENUWNDPLAYPROTECT_TRACE_MSG        0

#if (_UIMENUWNDPLAYPROTECT_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPlayProtectErrMsg(...)            debug_msg ("^R UIMenuWndPlayProtect: "__VA_ARGS__)
#else
#define UIMenuWndPlayProtectErrMsg(...)
#endif

#if (_UIMENUWNDPLAYPROTECT_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPlayProtectTraceMsg(...)          debug_msg ("^B UIMenuWndPlayProtect: "__VA_ARGS__)
#else
#define UIMenuWndPlayProtectTraceMsg(...)
#endif

//---------------------UIMenuWndPlayProtectCtrl Global Variables -----------------------------

//---------------------UIMenuWndPlayProtectCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPlayProtectCtrl Public API  ----------------------------------

//---------------------UIMenuWndPlayProtectCtrl Private API  ---------------------------------
//---------------------UIMenuWndPlayProtectCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayProtect)
CTRL_LIST_ITEM(UIMenuWndPlayProtect_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPlayProtect_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPlayProtectCtrl Event---------------------------
INT32 UIMenuWndPlayProtect_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayProtect)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayProtect_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayProtect_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayProtect_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayProtect_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayProtect_OnKeyMode)
EVENT_END

INT32 UIMenuWndPlayProtect_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxMenu_SetData(&UIMenuWndPlayProtect_MenuCtrl, MNU_CURITM, 0);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPlayProtectCtrl, 0); 	
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}

//---------------------UIMenuWndPlayProtect_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayProtect_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPlayProtect_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayProtect_BGMenu)
EVENT_END

//----------------------UIMenuWndPlayProtect_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayProtect_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayProtect_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayProtect_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayProtect_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayProtect_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayProtect_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_PROTECT_ONE);	
                    BKG_PostEvent(NVTEVT_BKW_SETPROTECT);
			
			break;
		case 1:
			AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_UNPROTECT_ONE);			
                    BKG_PostEvent(NVTEVT_BKW_SETPROTECT);
			break;		
		case 2:
			AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_PROTECT_ALL);			
                    BKG_PostEvent(NVTEVT_BKW_SETPROTECT);
			break;	
		case 3:
			AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_UNPROTECT_ALL);	
                    BKG_PostEvent(NVTEVT_BKW_SETPROTECT);			
			break;				
		default:
			break;
			
	}
	Ux_CloseWindow(&UIMenuWndPlayProtectCtrl, 0); 	
	   
    return NVTEVT_CONSUME;
}
