//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayVolumeRes.c"
#include "UIMenuWndPlayVolume.h"
#include "PrjCfg.h"
#include "UIFlow.h"

//---------------------UIMenuWndPlayVolumeCtrl Debug Definition -----------------------------
#define _UIMENUWNDPLAYVOLUME_ERROR_MSG        1
#define _UIMENUWNDPLAYVOLUME_TRACE_MSG        0

#if (_UIMENUWNDPLAYVOLUME_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPlayVolumeErrMsg(...)            debug_msg ("^R UIMenuWndPlayVolume: "__VA_ARGS__)
#else
#define UIMenuWndPlayVolumeErrMsg(...)
#endif

#if (_UIMENUWNDPLAYVOLUME_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPlayVolumeTraceMsg(...)          debug_msg ("^B UIMenuWndPlayVolume: "__VA_ARGS__)
#else
#define UIMenuWndPlayVolumeTraceMsg(...)
#endif

//---------------------UIMenuWndPlayVolumeCtrl Global Variables -----------------------------

//---------------------UIMenuWndPlayVolumeCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPlayVolumeCtrl Public API  ----------------------------------

//---------------------UIMenuWndPlayVolumeCtrl Private API  ---------------------------------
//---------------------UIMenuWndPlayVolumeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayVolume)
CTRL_LIST_ITEM(UIMenuWndPlayVolume_BGMenu)
CTRL_LIST_ITEM(UIMenuWndPlayVolume_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPlayVolumeCtrl Event---------------------------
INT32 UIMenuWndPlayVolume_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayVolume_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayVolume_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayVolume_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayVolume)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayVolume_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayVolume_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPlayVolume_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPlayVolume_OnKeyMode)
EVENT_END

INT32 UIMenuWndPlayVolume_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 Data;

	switch(UI_GetData(FL_MovieAudioPlayIndex))
	{
		case MOVIE_AUDIO_VOL_0:  
			Data = 0;
			break;
		case MOVIE_AUDIO_VOL_3:  
			Data = 1;
			break;
		case MOVIE_AUDIO_VOL_4:  
			Data = 2;
			break;	
		case MOVIE_AUDIO_VOL_5:  
			Data = 3;
			break;		
		case MOVIE_AUDIO_VOL_6:  
			Data = 4;
			break;
		case MOVIE_AUDIO_VOL_7:  
			Data = 5;
			break;	
		case MOVIE_AUDIO_VOL_8:  
			Data = 6;
			break;		
		case MOVIE_AUDIO_VOL_9:  
			Data = 7;
			break;
		case MOVIE_AUDIO_VOL_10:  
			Data = 8;
			break;					
		default:
			Data = 8;
			break;	
	}
	
	UxMenu_SetData(&UIMenuWndPlayVolume_MenuCtrl, MNU_CURITM, Data);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayVolume_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPlayVolume_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayVolume_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndPlayVolumeCtrl, 0);
	//Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayVolume_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayVolume_BGMenu)
CTRL_LIST_END

//----------------------UIMenuWndPlayVolume_BGMenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayVolume_BGMenu)
EVENT_END

//----------------------UIMenuWndPlayVolume_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayVolume_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayVolume_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayVolume_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayVolume_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayVolume_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayVolume_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayVolume_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayVolume_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayVolume_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayVolume_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiSelItem=UxMenu_GetData(pCtrl, MNU_CURITM); 

	debug_msg("\r\n uiSelItem:%d\r\n",uiSelItem);

	switch(uiSelItem)
	{
	
		case 0: 
			uiSelItem = MOVIE_AUDIO_VOL_0;
			break;
		case 1: 
			uiSelItem = MOVIE_AUDIO_VOL_3;
			break;

		case 2:
			uiSelItem = MOVIE_AUDIO_VOL_4;
			break;		
		case 3:
			uiSelItem = MOVIE_AUDIO_VOL_5;
			break;		
		case 4: 
			uiSelItem = MOVIE_AUDIO_VOL_6;
			break;

		case 5:
			uiSelItem = MOVIE_AUDIO_VOL_7;
			break;		
		case 6:
			uiSelItem = MOVIE_AUDIO_VOL_8;
			break;		
		case 7: 
			uiSelItem = MOVIE_AUDIO_VOL_9;
			break; 

		case 8:
			uiSelItem = MOVIE_AUDIO_VOL_10;
			break;		
				
		default:
			uiSelItem = MOVIE_AUDIO_VOL_10;
			break;
			
	}
	Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 1, uiSelItem);	   
	Ux_CloseWindow(&UIMenuWndPlayVolumeCtrl, 0);

    return NVTEVT_CONSUME;
}
