//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWRNACCPOWEROFFWAIT_H
#define UIFLOWWNDWRNACCPOWEROFFWAIT_H

#include "UIFramework.h"

extern VControl UIFlowWndAccPowerOffMsgCtrl;//Panel type 

extern VControl UIFlowWndAccPowerOff_MsgCtrl;//Static type 

#endif
