//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndWrnAccPowerOffWaitRes.c"
#include "UIFlowWndWrnAccPowerOffWait.h"
#include "PrjCfg.h"
#include "GxTimer.h"
#include "UIFlow.h"

//static UINT32   g_uiAccPoweroffWaitTimer = NULL_TIMER;
extern BOOL bAccPowerOff;
extern BOOL bEnterTimelapse;
extern BOOL bPlaybackChangeModeAutoRec;

//---------------------UIFlowWndAccPowerOffMsgCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndAccPowerOffMsg)
CTRL_LIST_ITEM(UIFlowWndAccPowerOff_Msg)
CTRL_LIST_END

//----------------------UIFlowWndAccPowerOffMsgCtrl Event---------------------------
INT32 UIFlowWndAccPowerOffMsg_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAccPowerOffMsg_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAccPowerOffMsg_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAccPowerOffMsg_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAccPowerOffMsg_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAccPowerOffMsg_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAccPowerOffMsg_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndAccPowerOffMsg)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndAccPowerOffMsg_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndAccPowerOffMsg_OnClose)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndAccPowerOffMsg_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndAccPowerOffMsg_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndAccPowerOffMsg_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndAccPowerOffMsg_OnKeyPlayback)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndAccPowerOffMsg_OnTimer)
EVENT_END

void AccPowerOffMsgUpdata(void)
{
	static char poweroffinfo[32];
	static UINT32 poweroffcount = 10;
	if(poweroffcount>0)
		poweroffcount--;
	snprintf(poweroffinfo, sizeof(poweroffinfo), "PowerOff... %dS", poweroffcount);
	UxStatic_SetData(&UIFlowWndAccPowerOff_MsgCtrl, STATIC_VALUE, Txt_Pointer(poweroffinfo));
	UxCtrl_SetShow(&UIFlowWndAccPowerOff_MsgCtrl, TRUE);


	if(poweroffcount <=0)
	{
		if(bEnterTimelapse)
		{
			bPlaybackChangeModeAutoRec = TRUE;
			if (SysGetFlag(FL_MOVIE_TIMELAPSE_REC)==MOVIE_TIMELAPSEREC_OFF)
				SysSetFlag(FL_MOVIE_TIMELAPSE_REC,MOVIE_TIMELAPSEREC_1SEC);
			//Ux_CloseWindow(&UIFlowWndAccPowerOffMsgCtrl, 0);
			Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, PRIMARY_MODE_MOVIE, SYS_SUBMODE_NORMAL);
		}
		else
		{
			bAccPowerOff = TRUE;
	    	Ux_PostEvent(NVTEVT_KEY_POWER_REL, 1, NVTEVT_KEY_RELEASE);
		}
	}


}

INT32 UIFlowWndAccPowerOffMsg_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
    /*if (g_uiAccPoweroffWaitTimer == NULL_TIMER)
    {
        g_uiAccPoweroffWaitTimer = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
    }*/
	AccPowerOffMsgUpdata();
	
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAccPowerOffMsg_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /*if (g_uiAccPoweroffWaitTimer != NULL_TIMER)
    {
        GxTimer_StopTimer(&g_uiAccPoweroffWaitTimer);
    }*/

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAccPowerOffMsg_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAccPowerOffMsg_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAccPowerOffMsg_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAccPowerOffMsg_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAccPowerOffMsg_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;

    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    {
    	case NVTEVT_1SEC_TIMER:
			AccPowerOffMsgUpdata();
        	break;
    }
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndAccPowerOff_MsgCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndAccPowerOff_Msg)
EVENT_END

