//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiMobileConfirmDisconnectRes.c"
#include "UIMenuWndWiFiMobileConfirmDisconnect.h"
#include "PrjCfg.h"
#include "UIFramework.h"
#include "UIAppWiFiCmd.h"
#include "AppLib.h"
#include "UIFlow.h"
#include "WifiAppCmd.h"
//---------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIMOBILECONFIRMDISCONNECT_ERROR_MSG        1
#define _UIMENUWNDWIFIMOBILECONFIRMDISCONNECT_TRACE_MSG        0

#if (_UIMENUWNDWIFIMOBILECONFIRMDISCONNECT_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiMobileConfirmDisconnectErrMsg(...)            debug_msg ("^R UIMenuWndWiFiMobileConfirmDisconnect: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileConfirmDisconnectErrMsg(...)
#endif

#if (_UIMENUWNDWIFIMOBILECONFIRMDISCONNECT_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiMobileConfirmDisconnectTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiMobileConfirmDisconnect: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileConfirmDisconnectTraceMsg(...)
#endif

//---------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl Global Variables -----------------------------

//---------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileConfirmDisconnect)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileConfirmDisconnect_Static_Text)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileConfirmDisconnect_List_Text)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileConfirmDisconnect_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileConfirmDisconnect_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileConfirmDisconnect)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndWiFiMobileConfirmDisconnect_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndWiFiMobileConfirmDisconnect_OnClose)
EVENT_END

INT32 UIMenuWndWiFiMobileConfirmDisconnect_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileConfirmDisconnect_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileConfirmDisconnect_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileConfirmDisconnect_Static_Text)
EVENT_END

//----------------------UIMenuWndWiFiMobileConfirmDisconnect_List_TextCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileConfirmDisconnect_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiEvtKeyAct = 0;

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];

    switch(uiEvtKeyAct)
    {
        case NVTEVT_KEY_PRESS:
			Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
             break;
        case NVTEVT_KEY_RELEASE:
        default:
            break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiEvtKeyAct = 0;
	
	   if(paramNum > 0)
		   uiEvtKeyAct = paramArray[0];
	
	   switch(uiEvtKeyAct)
	   {
		   case NVTEVT_KEY_PRESS:
			   Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
				break;
		   case NVTEVT_KEY_RELEASE:
		   default:
			   break;
	
	   }		 
    return NVTEVT_CONSUME;
}
extern void System_ChangeToNormalMode(void);
INT32 UIMenuWndWiFiMobileConfirmDisconnect_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	if (UxList_GetData(pCtrl, LST_CURITM) == UIMenuWndWiFiMobileConfirmDisconnect_List_Text_STRID_OK){
		
		UINT32	uiKeyAct;
		uiKeyAct = paramArray[0];
		switch(uiKeyAct)
		{
			case NVTEVT_KEY_PRESS:				
				System_ChangeToNormalMode();
				//Ux_PostEvent(NVTEVT_WIFI_EXE_APP_SESSION_CLOSE, 0);
				//should close network application,then stop wifi
				//zjf reopen wifi
				WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
				Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
				Delay_DelayMs(100);
				Ux_PostEvent(NVTEVT_EXE_WIFI_START, 0);
			break;
		}
	}else{
		Ux_CloseWindow(&UIMenuWndWiFiMobileConfirmDisconnectCtrl, 0);
	}
    return NVTEVT_CONSUME;
}
