//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIMOBILECONFIRMDISCONNECT_H
#define UIMENUWNDWIFIMOBILECONFIRMDISCONNECT_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiMobileConfirmDisconnectCtrl;//Panel type 

extern VControl UIMenuWndWiFiMobileConfirmDisconnect_Static_TextCtrl;//Static type 

extern VControl UIMenuWndWiFiMobileConfirmDisconnect_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndWiFiMobileConfirmDisconnect_List_Text_STRID_CANCEL,
UIMenuWndWiFiMobileConfirmDisconnect_List_Text_STRID_OK,
UIMenuWndWiFiMobileConfirmDisconnect_List_Text_MAX
}UIMenuWndWiFiMobileConfirmDisconnect_List_Text_Setting;

//---------------------UIMenuWndWiFiMobileConfirmDisconnectCtrl User Export---------------------------
#endif
