//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIWAIT_H
#define UIMENUWNDWIFIWAIT_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiWaitCtrl;//Panel type 

extern VControl UIMenuWndWiFiWait_Connect_Text_StaticCtrl;//Static type 

//---------------------UIMenuWndWiFiWaitCtrl User Export---------------------------
#endif
