//This source code is generated by UI Designer Studio.

#include "stdio.h"
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiMobileLinkOKRes.c"
#include "WifiAppCmd.h"
#include "UIFlow.h"
#include "UIAppNetwork.h"
#include "ImageApp_MovieMulti.h"

//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
#include "ImageUnit_UsbUVAC.h"
#include "UsbCmdAPI.h"
#endif
#include "ImageApp_MovieCommon.h"
#if(USER_WATCH_DOG==ENABLE)
#include "wdt.h"
#endif
#include "DxOutput.h"

//#NT#2016/05/31#Ben Wang -end
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG        1
#define _UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG        1

#if (_UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)            debug_msg ("^R UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)
#endif

#if (_UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)
#endif


#define LINKOK_KEY_PRESS_MASK        (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_MODE|FLGKEY_ENTER|FLGKEY_MENU)
#define LINKOK_KEY_RELEASE_MASK      (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_MODE|FLGKEY_ENTER|FLGKEY_MENU)
#define LINKOK_KEY_CONTINUE_MASK     (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_MODE|FLGKEY_ENTER|FLGKEY_MENU)

//static UINT32  g_uiLinkokMaskKeyPress      = LINKOK_KEY_PRESS_MASK;
//static UINT32  g_uiLinkokMaskKeyRelease    = LINKOK_KEY_RELEASE_MASK;
//static UINT32  g_uiLinkokMaskKeyContinue    = LINKOK_KEY_CONTINUE_MASK;

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Global Variables -----------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkSts)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Button_Disconnect)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticTXT_MAC)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_camera)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_WIFI)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_time)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_resolution)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Storage)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_CyclicRec)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusICN_EV)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_YMD_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_HMS_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_REC)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Lock)

CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_ALG_Draw)
CTRL_LIST_END
char StringTmpBuf[32] = {0};
//----------------------UIMenuWndWiFiMobileLinkOKCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *, UINT32, UINT32 *);

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeChangeModeDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyCustom1(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyLock(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyCapture(VControl *, UINT32 , UINT32 *);

INT32 UIMenuWndWiFiMobileLinkOK_OnKeyUp(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyDown(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyEnter(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyMode(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyMenu(VControl *, UINT32 , UINT32 *);

INT32 UIMenuWndWiFiMobileLinkOK_OnKeyShutter2(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey1Test(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey2Test(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey3Test(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey4Test(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeLEDTest(VControl *, UINT32 , UINT32 *);

INT32 UIMenuWndWiFiMobileLinkOK_OnExeEMRComplete(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
INT32 UIMenuWndWiFiMobileLinkOK_OnEnterAccOffTimelapse(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndWiFiMobileLinkOK_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndWiFiMobileLinkOK_OnClose)
EVENT_ITEM(NVTEVT_WIFI_AUTHORIZED_OK, UIMenuWndWiFiMobileLinkOK_Authorized_OK)
EVENT_ITEM(NVTEVT_WIFI_DHCP_REQ, UIMenuWndWiFiMobileLinkOK_DHCP_REQ)

EVENT_ITEM(NVTEVT_STORAGE_INIT, UIMenuWndWiFiModuleLinkOK_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, UIMenuWndWiFiModuleLinkOK_OnStorageChange)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE, UIMenuWndWiFiMobileLinkOK_OnBackgroundDone)
EVENT_ITEM(NVTEVT_CB_MOVIE_OVERTIME, UIMenuWndWiFiMobileLinkOK_OnMovieFull) // the same handling as storage full (may need to show special message)
EVENT_ITEM(NVTEVT_CB_MOVIE_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_LOOPREC_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_WR_ERROR, UIMenuWndWiFiMobileLinkOK_OnMovieWrError)
EVENT_ITEM(NVTEVT_CB_MOVIE_SLOW, UIMenuWndWiFiMobileLinkOK_OnStorageSlow)
EVENT_ITEM(NVTEVT_CB_MOVIE_REC_ONE_SEC, UIMenuWndWiFiMobileLinkOK_OnMovieOneSec)
EVENT_ITEM(NVTEVT_CB_RAWENC_OK, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB)
EVENT_ITEM(NVTEVT_CB_RAWENC_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_WRITE_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_DCF_FULL, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_BATTERY_LOW, UIMenuWndWiFiMobileLinkOK_OnBatteryLow)
EVENT_ITEM(NVTEVT_WIFI_DEAUTHENTICATED, UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated)
EVENT_ITEM(NVTEVT_CB_MOVIE_VEDIO_READY, UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady)
EVENT_ITEM(NVTEVT_TIMER, UIMenuWndWiFiMobileLinkOK_OnTimer)
EVENT_ITEM(NVTEVT_KEY_CUSTOM1, UIMenuWndWiFiMobileLinkOK_OnKeyCustom1)
EVENT_ITEM(NVTEVT_KEY_LOCK, UIMenuWndWiFiMobileLinkOK_OnKeyLock)
EVENT_ITEM(NVTEVT_KEY_CAPTURE, UIMenuWndWiFiMobileLinkOK_OnKeyCapture)

EVENT_ITEM(NVTEVT_KEY_UP, UIMenuWndWiFiMobileLinkOK_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN, UIMenuWndWiFiMobileLinkOK_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIMenuWndWiFiMobileLinkOK_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndWiFiMobileLinkOK_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndWiFiMobileLinkOK_OnKeyMenu)

EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIMenuWndWiFiMobileLinkOK_OnKeyShutter2)
//for factory test
EVENT_ITEM(NVTEVT_WIFI_EXE_KEY1,UIMenuWndWiFiMobileLinkOK_OnExeKey1Test)
EVENT_ITEM(NVTEVT_WIFI_EXE_KEY2,UIMenuWndWiFiMobileLinkOK_OnExeKey2Test)
EVENT_ITEM(NVTEVT_WIFI_EXE_KEY3,UIMenuWndWiFiMobileLinkOK_OnExeKey3Test)
EVENT_ITEM(NVTEVT_WIFI_EXE_KEY4,UIMenuWndWiFiMobileLinkOK_OnExeKey4Test)
EVENT_ITEM(NVTEVT_WIFI_EXE_LED,UIMenuWndWiFiMobileLinkOK_OnExeLEDTest)

EVENT_ITEM(NVTEVT_CB_EMR_COMPLETED, UIMenuWndWiFiMobileLinkOK_OnExeEMRComplete)
EVENT_ITEM(NVTEVT_ACC_OFF_TIMELAPSE, UIMenuWndWiFiMobileLinkOK_OnEnterAccOffTimelapse)
EVENT_END



extern char gLastMacAddr[];
extern BOOL gWifiAutoRec;

static CHAR    g_RecMaxTimeStr[20] = {0};
static UINT32  g_RecMaxTime = 0;
static CHAR    g_RecCurrTimeStr[20] = {0};
static UINT32  g_RecCurrTime = 0;
static CHAR    date_str[20] = {0};
static CHAR    time_str[20] = {0};

//for factory test
static BOOL bKey1TestBegin = FALSE;
static BOOL bKey2TestBegin = FALSE;
static BOOL bKey3TestBegin = FALSE;
static BOOL bKey4TestBegin = FALSE;

BOOL bLEDTestBegin = FALSE;
static UINT32 uiFactoryTestKeyTimerID = NULL_TIMER;
extern UINT32  gUIWifiAutoRecTimerID;
extern BOOL g_bRecordLock;
extern BOOL	g_uiRecordIngMotionDet;

//MOVIE_SIZE_TAG
static CHAR    *resolution_Buf[MOVIE_SIZE_ID_MAX] = {
	[MOVIE_SIZE_FRONT_2880x2160P50] = "UHD P50",
	[MOVIE_SIZE_FRONT_3840x2160P30] = "UHD P30",
	[MOVIE_SIZE_FRONT_2880x2160P24] = "UHD P24",
	[MOVIE_SIZE_FRONT_2704x2032P60] = "2.7K P60",
	//[MOVIE_SIZE_FRONT_2560x1600P30] = "2560x1600 P30",
	[MOVIE_SIZE_FRONT_2560x1440P80] = "QHD P80",
	[MOVIE_SIZE_FRONT_2560x1440P60] = "QHD P60",
	[MOVIE_SIZE_FRONT_2560x1440P30] = "QHD P30",
	[MOVIE_SIZE_FRONT_2304x1296P30] = "3MHD P30",
	[MOVIE_SIZE_FRONT_1920x1080P120] = "FHD P120",
	[MOVIE_SIZE_FRONT_1920x1080P96] = "FHD P96",
	[MOVIE_SIZE_FRONT_1920x1080P60] = "FHD P60",
	//[MOVIE_SIZE_FRONT_1920x1080P30] = "FHD P30",
	[MOVIE_SIZE_FRONT_1920x1080P30] = "1080P",
	[MOVIE_SIZE_FRONT_1280x720P120] = "HD P120",
	[MOVIE_SIZE_FRONT_1280x720P240] = "HD P240",
	[MOVIE_SIZE_FRONT_1280x720P60] = "HD P60",
	//[MOVIE_SIZE_FRONT_1280x720P30] = "HD P30",
	[MOVIE_SIZE_FRONT_1280x720P30] = "720P",
	//[MOVIE_SIZE_FRONT_848x480P30] = "WVGA P30",
	[MOVIE_SIZE_FRONT_848x480P30] = "WVGA",
	[MOVIE_SIZE_FRONT_640x480P240] = "VGA P240",
	[MOVIE_SIZE_FRONT_640x480P30] = "VGA P30",
	[MOVIE_SIZE_FRONT_320x240P30] = "QVGA P30",
	[MOVIE_SIZE_DUAL_2560x1440P30_1280x720P30] = "QHD P30+HD P30",
	[MOVIE_SIZE_DUAL_2560x1440P30_1920x1080P30] = "1440P+1080P",//pqw
	[MOVIE_SIZE_DUAL_2304x1296P30_1280x720P30] = "3MHD P30+HD P30",
	[MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30] = "1080P+1080P",//"FHD P30+FHD P30",
	[MOVIE_SIZE_DUAL_1280x720P30_1920x1080P30] = "720P+1080P",
	[MOVIE_SIZE_DUAL_1920x1080P30_1280x720P30] = "FHD P30+HD P30",
	[MOVIE_SIZE_DUAL_1920x1080P30_848x480P30] = "FHD P30+WVGA P30",
	[MOVIE_SIZE_CLONE_1920x1080P30_1920x1080P30] = "FHD P30+FHD P30",
	[MOVIE_SIZE_CLONE_1920x1080P30_1280x720P30] = "FHD P30+HD P30",
	//[MOVIE_SIZE_CLONE_2560x1600P30_848x480P30] = "1600 P30+WVGA P30",
	[MOVIE_SIZE_CLONE_2560x1440P30_848x480P30] = "QHD P30+WVGA P30",
	[MOVIE_SIZE_CLONE_2304x1296P30_848x480P30] = "3MHD P30+WVGA P30",
	[MOVIE_SIZE_CLONE_1920x1080P60_848x480P30] = "FHD P60+WVGA P30",
	[MOVIE_SIZE_CLONE_1920x1080P60_640x360P30] = "FHD P60+VGA P30",
	[MOVIE_SIZE_CLONE_1920x1080P30_848x480P30] = "FHD P30+WVGA P30",
	[MOVIE_SIZE_CLONE_2048x2048P30_480x480P30] = "2048x2048 P30 + 480x480 P30",
};

void FlowWifiMovie_IconDrawDscMode(VControl *pCtrl)
{
	UxCtrl_SetShow(pCtrl, TRUE);
}

void FlowWifiMovie_IconHideDscMode(VControl *pCtrl)
{
	UxCtrl_SetShow(pCtrl, FALSE);
}

void FlowWifiMovie_IconDrawMaxRecTime(VControl *pCtrl)
{
	if (GxStrg_GetDevice(0) == NULL) {

		snprintf(g_RecMaxTimeStr, 20, "00:00:00", 0, 0, 0);
		UxStatic_SetData(pCtrl, STATIC_VALUE, Txt_Pointer(g_RecMaxTimeStr));
		UxCtrl_SetShow(pCtrl, TRUE);
		//No Storage, direct to return.
		return;
	}

	memset((void *)g_RecMaxTimeStr, 0, sizeof(g_RecMaxTimeStr));
	g_RecMaxTime = MovieExe_GetMaxRecSec();

	if (g_RecMaxTime <= 2) {
		FlowMovie_SetRecMaxTime(0);
	} else if (g_RecMaxTime > 86399) {
		///23:59:59
		FlowMovie_SetRecMaxTime(86399);
	} else {
		FlowMovie_SetRecMaxTime(g_RecMaxTime);
	}

	if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED) {
		snprintf(g_RecMaxTimeStr, 20, "%02d:%02d:%02d", 0, 0, 0);
	} else {
		snprintf(g_RecMaxTimeStr, 20, "%02d:%02d:%02d", g_RecMaxTime / 3600, (g_RecMaxTime % 3600) / 60, (g_RecMaxTime % 3600) % 60);
	}

	UxStatic_SetData(pCtrl, STATIC_VALUE, Txt_Pointer(g_RecMaxTimeStr));
	UxCtrl_SetShow(pCtrl, TRUE);
}

void FlowWifiMovie_IconHideMaxRecTime(VControl *pCtrl)
{
	UxCtrl_SetShow(pCtrl, FALSE);
}

void FlowWifiMovie_IconDrawRecTime(VControl *pCtrl)
{
//#NT#2016/03/07#KCHong -begin
//#NT#Low power timelapse function
#if (TIMELAPSE_LPR_FUNCTION == ENABLE)
	UINT32 TimelapseMode = 0;
#endif
//#NT#2016/03/07#KCHong -end
	//#NT#2016/03/07#KCHong -begin
	//#NT#Low power timelapse function
#if (TIMELAPSE_LPR_FUNCTION == ENABLE)
	if (MovieTLLPR_GetStatus() == (TL_FLOW_LPR | TL_STATE_RECORD)) {
		TimelapseMode = UI_GetData(FL_MOVIE_TIMELAPSE_REC);
		if (TimelapseMode >= TL_LPR_TIME_MIN_PERIOD) {
			if (TimelapseMode == MOVIE_TIMELAPSEREC_OFF) {
				snprintf(g_RecCurrTimeStr, 20, "OFF");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_1SEC) {
				snprintf(g_RecCurrTimeStr, 20, "1 SEC");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_5SEC) {
				snprintf(g_RecCurrTimeStr, 20, "5 SEC");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_10SEC) {
				snprintf(g_RecCurrTimeStr, 20, "10 SEC");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_30SEC) {
				snprintf(g_RecCurrTimeStr, 20, "30 SEC");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_1MIN) {
				snprintf(g_RecCurrTimeStr, 20, "1 MIN");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_5MIN) {
				snprintf(g_RecCurrTimeStr, 20, "5 MIN");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_10MIN) {
				snprintf(g_RecCurrTimeStr, 20, "10 MIN");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_30MIN) {
				snprintf(g_RecCurrTimeStr, 20, "30 MIN");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_1HOUR) {
				snprintf(g_RecCurrTimeStr, 20, "1 HOUR");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_2HOUR) {
				snprintf(g_RecCurrTimeStr, 20, "2 HOUR");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_3HOUR) {
				snprintf(g_RecCurrTimeStr, 20, "3 HOUR");
			} else if (TimelapseMode == MOVIE_TIMELAPSEREC_1DAY) {
				snprintf(g_RecCurrTimeStr, 20, "1 DAY");
			}
			UxStatic_SetData(pCtrl, STATIC_VALUE, Txt_Pointer(g_RecCurrTimeStr));
			UxCtrl_SetShow(pCtrl, TRUE);
			break;
		}
	}
#endif
	//#NT#2016/03/07#KCHong -end
	g_RecCurrTime = FlowMovie_GetRecCurrTime();
	memset((void *)g_RecCurrTimeStr, 0, sizeof(g_RecCurrTimeStr));
	snprintf(g_RecCurrTimeStr, 20, "%02d:%02d:%02d", g_RecCurrTime / 3600, (g_RecCurrTime % 3600) / 60, (g_RecCurrTime % 3600) % 60);
	UxStatic_SetData(pCtrl, STATIC_VALUE, Txt_Pointer(g_RecCurrTimeStr));
	UxCtrl_SetShow(pCtrl, TRUE);
}

void FlowWifiMovie_IconDrawDateTime(void)
{
    struct tm Curr_DateTime;
    Curr_DateTime = HwClock_GetTime(TIME_ID_CURRENT);
	// display Date/Time string in movie mode
	snprintf(date_str, 20, "%04d/%02d/%02d", Curr_DateTime.tm_year, Curr_DateTime.tm_mon, Curr_DateTime.tm_mday);
	snprintf(time_str, 20, "%02d:%02d:%02d", Curr_DateTime.tm_hour, Curr_DateTime.tm_min, Curr_DateTime.tm_sec);
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_YMD_StaticCtrl, STATIC_VALUE, Txt_Pointer(date_str));
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_HMS_StaticCtrl, STATIC_VALUE, Txt_Pointer(time_str));
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_YMD_StaticCtrl, TRUE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_HMS_StaticCtrl, TRUE);
}

void FlowWifiMovie_IconHideDateTime(void)
{
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_YMD_StaticCtrl, FALSE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_HMS_StaticCtrl, FALSE);
}

void FlowWifiMovie_IconDrawRec(VControl *pCtrl)
{
	UxState_SetData(pCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_REC_ICON_REC_TRANSPAENT);
}

void FlowWifiMovie_IconHideRec(VControl *pCtrl)
{
	UxState_SetData(pCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_REC_ICON_REC_TRANSPAENT);
}

void FlowWifiMovie_IconDrawSize(VControl *pCtrl)
{
	UxStatic_SetData(pCtrl, STATIC_VALUE, Txt_Pointer(resolution_Buf[SysGetFlag(FL_MOVIE_SIZE)]));
	UxCtrl_SetShow(pCtrl, TRUE);
}

void FlowWifiMovie_IconHideSize(VControl *pCtrl)
{
	UxCtrl_SetShow(pCtrl, FALSE);
}

void FlowWifiMovie_IconDrawEV(VControl *pCtrl)
{
	UxState_SetData(pCtrl, STATE_CURITEM, SysGetFlag(FL_EV));
	UxCtrl_SetShow(pCtrl, TRUE);
}

void FlowWifiMovie_IconHideEV(VControl *pCtrl)
{
	UxCtrl_SetShow(pCtrl, FALSE);
}

void FlowWifiMovie_IconDrawStorage(VControl *pCtrl)
{
	/* Update status item data */
	if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED) {
		UxState_SetData(pCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Storage_ICON_INTERNAL_FLASH);
	} else if (System_GetState(SYS_STATE_CARD)  == CARD_LOCKED) {
		UxState_SetData(pCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Storage_ICON_SD_LOCK);
	} else {
		UxState_SetData(pCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Storage_ICON_SD_CARD);
	}

	UxCtrl_SetShow(pCtrl, TRUE);
}

void FlowWifiMovie_IconHideStorage(VControl *pCtrl)
{
	UxCtrl_SetShow(pCtrl, FALSE);
}

void FlowWifiMovie_IconDrawCyclicRec(VControl *pCtrl)
{
	UxState_SetData(pCtrl, STATE_CURITEM, SysGetFlag(FL_MOVIE_CYCLIC_REC));
	UxCtrl_SetShow(pCtrl, TRUE);
}

void FlowWifiMovie_IconHideCyclicRec(VControl *pCtrl)
{
	UxCtrl_SetShow(pCtrl, FALSE);
}
void FlowWifiMovie_DrawWifi(BOOL bDraw)
{  
    UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_WIFICtrl, STATE_CURITEM, 2);        
    UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_WIFICtrl, bDraw);    
}

void FlowWifiMovie_DrawLock(BOOL bDraw)
{  
    if(bDraw)
    {
       UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_LockCtrl, STATE_CURITEM, 1); 	
       UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_LockCtrl, bDraw);
    }
    else
    {
       UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_LockCtrl, STATE_CURITEM, 0); 	
       UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_LockCtrl, bDraw); 	 
    }
}


void FlowWifiMovie_UpdateIcons(BOOL bShow)
{
	if (bShow == FALSE || SysGetFlag(FL_LCD_DISPLAY) == DISPOUT_OFF) {
		FlowWifiMovie_IconHideDscMode(&UIMenuWndWiFiMobileLinkOK_Status_WIFICtrl);
		FlowWifiMovie_IconHideSize(&UIMenuWndWiFiMobileLinkOK_Static_resolutionCtrl);
		FlowWifiMovie_IconHideMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl);
		FlowWifiMovie_IconHideRec(&UIMenuWndWiFiMobileLinkOK_Status_RECCtrl);
		FlowWifiMovie_IconHideStorage(&UIMenuWndWiFiMobileLinkOK_Status_StorageCtrl);
		FlowWifiMovie_IconHideCyclicRec(&UIMenuWndWiFiMobileLinkOK_Status_CyclicRecCtrl);
        FlowWifiMovie_IconHideEV(&UIMenuWndWiFiMobileLinkOK_StatusICN_EVCtrl);
		FlowWifiMovie_IconHideDateTime();
	} else {
		FlowWifiMovie_IconDrawDscMode(&UIMenuWndWiFiMobileLinkOK_Static_cameraCtrl);
		FlowWifiMovie_IconDrawSize(&UIMenuWndWiFiMobileLinkOK_Static_resolutionCtrl);
		FlowWifiMovie_IconDrawMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl);
		FlowWifiMovie_IconHideRec(&UIMenuWndWiFiMobileLinkOK_Status_RECCtrl);
		FlowWifiMovie_IconDrawStorage(&UIMenuWndWiFiMobileLinkOK_Status_StorageCtrl);
		FlowWifiMovie_IconDrawCyclicRec(&UIMenuWndWiFiMobileLinkOK_Status_CyclicRecCtrl);
		FlowWifiMovie_IconDrawEV(&UIMenuWndWiFiMobileLinkOK_StatusICN_EVCtrl);
		FlowWifiMovie_IconDrawDateTime();	
		FlowWifiMovie_DrawWifi(TRUE);	
	}
}

void FlowWifiMovie_UpdateIconsOneSec(void)
{
   FlowWifiMovie_IconDrawSize(&UIMenuWndWiFiMobileLinkOK_Static_resolutionCtrl); 
   FlowWifiMovie_IconDrawCyclicRec(&UIMenuWndWiFiMobileLinkOK_Status_CyclicRecCtrl); 
   FlowWifiMovie_IconDrawEV(&UIMenuWndWiFiMobileLinkOK_StatusICN_EVCtrl); 
   FlowWifiMovie_IconDrawStorage(&UIMenuWndWiFiMobileLinkOK_Status_StorageCtrl);
   FlowWifiMovie_IconDrawDateTime();	

}


//#Miotone#Liwk -20161201 -begin
//reduce Rawenc Task Busy Problem!

static UINT32 gUIWifiRawEncTimerID = NULL_TIMER;
void _WifiMobileLinkOK_StartSnapShotTimer(void)
{
    gUIWifiRawEncTimerID = GxTimer_StartTimer(2000, NVTEVT_SNAPSHOT_TIMER, ONE_SHOT);//4 //4 sec  
}
void _WifiMobileLinkOK_StopSnapShotTimer(void)
{
   if(gUIWifiRawEncTimerID != NULL_TIMER)
   {
      GxTimer_StopTimer(&gUIWifiRawEncTimerID);
   }
}
//#Miotone#Liwk -20161201 -end


void UIMenuWndWiFiMobileLinkOK_SyncRecStatus(void)
{
	if (WiFiCmd_GetStatus() == WIFI_MOV_ST_RECORD)
	{
	   gMovData.State = MOV_ST_REC;
	}
	else
	{
	   gMovData.State = MOV_ST_VIEW; 
	}
}

static UINT32  g_uiWifiDateTimerID = NULL_TIMER;
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
	static char Buf1[32] = {0}, buf2[32] = {0} ;

	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	//Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
	//Input_SetKeyMask(KEY_RELEASE, 0);
	//Input_SetKeyMask(KEY_CONTINUE, 0);
	Input_SetKeyMask(KEY_PRESS, LINKOK_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, LINKOK_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, LINKOK_KEY_CONTINUE_MASK);
	
	#if(USER_WATCH_DOG==ENABLE)
    SysStartWDT();
    SysFeedWDT();
    #endif

//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, ISF_CTRL, UVAC_PARAM_CDC_ENABLE)) {
			MEM_RANGE WorkBuf;
			WorkBuf.Addr = OS_GetMempoolAddr(POOL_ID_USBCMD);
			WorkBuf.Size = POOL_SIZE_USBCMD;
			UsbCmd_Open(&WorkBuf);
		}
		snprintf(Buf1, sizeof(Buf1), "UVC Connected");
		//just don't show this string
		StringTmpBuf[0] = 0;
	} else
#endif
	{
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
		snprintf(Buf1, sizeof(Buf1), "WiFi Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %s", UINet_GetConnectedMAC());
#else
		snprintf(Buf1, sizeof(Buf1), "Ethernet Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " IP : %s", UINet_GetIP());
#endif
	}
//#NT#2016/05/31#Ben Wang -end
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl, STATIC_VALUE, Txt_Pointer(Buf1));
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));

	snprintf(buf2, sizeof(buf2), "Press Select to Disconnect");
	UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl, 0, BTNITM_STRID, Txt_Pointer(buf2));

//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) != SYS_SUBMODE_UVC)
#endif
	{
		//make sure, connec to RTSP mode
		if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
			Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
		}
	}
//#NT#2016/05/31#Ben Wang -end
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0 || WIFI_UI_DIRECT_MOBILE_LINKOK == ENABLE)
	WiFiCmd_HBStart();
#endif
//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStart();
	FlowWifiMovie_UpdateIcons(TRUE);
	FlowWifiMovie_DrawLock(FALSE);

	if (g_uiWifiDateTimerID == NULL_TIMER) {
		g_uiWifiDateTimerID = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_WIFI_UI_TIMER, CONTINUE);
	}
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
extern BOOL bAutoRecFirstTime;
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (UI_GetData(FL_MOVIE_SIZE_MENU) != UI_GetData(FL_MOVIE_SIZE)) {
		Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIESIZE, 1, UI_GetData(FL_MOVIE_SIZE_MENU));
	}
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0 || WIFI_UI_DIRECT_MOBILE_LINKOK == ENABLE)
	WiFiCmd_HBStop();
#endif

if (gUIWifiAutoRecTimerID != NULL_TIMER) {
	 GxTimer_StopTimer(&gUIWifiAutoRecTimerID);
}


//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStop();

//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	//if(System_GetState(SYS_STATE_CURRSUBMODE)==SYS_SUBMODE_UVC && System_GetState(SYS_STATE_NEXTSUBMODE)!=SYS_SUBMODE_UVC)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, ISF_CTRL, UVAC_PARAM_CDC_ENABLE)) {
			UsbCmd_Close();
		}
	}
#endif
//#NT#2016/05/31#Ben Wang -end
	//#NT#2019/10/30#Philex Lin - begin
	// stop re-connect timer in station mode
	if (UI_GetData(FL_NetWorkMode) == NET_STATION_MODE)
	    UINet_CliReConnect(0);
	//#NT#2019/10/30#Philex Lin - end
	
	#if(USER_WATCH_DOG==ENABLE)
	SysStartWDT();
	SysFeedWDT();
	#endif
	
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	bAutoRecFirstTime = FALSE;
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 bNewUser = 0 ;
	if (paramNum) {
		bNewUser = paramArray[0];
	}
#if 0  //print MAC when client get IP
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %s", UINet_GetConnectedMAC());
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#endif
	if (bNewUser) {
		//delay 500 ms,disconnect last user and
		//in window,use GxTimer replace Timer Delay,it would occupat UI task
		GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DISCONNECT_LAST_TIMER, ONE_SHOT);
	}

#if 0 // Moved to UINet_DhcpSrvCBCliConn.
	//make sure, connec to RTSP mode
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
	}
#endif

	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	char *pMAC = 0;
	if (paramNum) {
		pMAC = (char *)paramArray[0];
	}
	//#NT#2016/12/27#YongChang Qui -begin
	//#NT#don't display mac address on UI if mac is 0:0:0:0:0:0:0
	if (pMAC && (pMAC[0] || pMAC[1] || pMAC[2] || pMAC[3] || pMAC[4] || pMAC[5]))
		//#NT#2016/12/27#YongChang Qui -end
	{
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %02x%02x%02x%02x%02x%02x", pMAC[0], pMAC[1], pMAC[2]\
				 , pMAC[3], pMAC[4], pMAC[5]);
		UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		UIMenuWndWiFiMobileLinkOKTraceMsg("card err,removed\r\n");
	} else {
		UIMenuWndWiFiMobileLinkOKTraceMsg("card insert\r\n");
		if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) {
			Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
		} else {
			ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_REOPEN, 0);
		}
		WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_INSERT);
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	UIMenuWndWiFiMobileLinkOKTraceMsg("card removed\r\n");
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_PLAYBACK) {
		ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_CLOSE, 0);
	}
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_REMOVE);
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	NVTEVT event;
	UINT32 status;

	event = paramArray[ONDONE_PARAM_INDEX_CMD];
	status = paramArray[ONDONE_PARAM_INDEX_RET];
	debug_err(("%s event = 0x%x, status=%d\r\n", __FUNCTION__, event, status));

	switch (event) {
	case NVTEVT_BKW_FORMAT_CARD: {
		    //if(!status)
		      //System_SetStorageStatus(0);
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FORMAT_NAND: {
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FW_UPDATE: {
			if (status) {
				debug_err(("%s:update FW fail %d\r\n", __FUNCTION__, status));
				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, status + WIFIAPP_RET_FW_OFFSET);
			} else {
				//#NT#2016/03/23#Isiah Chang -begin
				//#NT#add new Wi-Fi UI flow.
				INT32 ret;

				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, WIFIAPP_RET_OK);

				ret = FileSys_DeleteFile(FW_UPDATE_NAME);
				if (ret != FST_STA_OK) {
					debug_err(("%s:delete FW fail %d\r\n", __FUNCTION__, status));
				}
				//#NT#2016/03/23#Isiah Chang -end
				Delay_DelayMs(2000);
				// Should power off immediatelly
				System_PowerOff(SYS_POWEROFF_NORMAL);
			}
			break;
		}

	default:
		debug_err(("%s:Unknown event 0x%x\r\n", __FUNCTION__, event));
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Full");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));
	return WiFiCmd_OnMovieFull(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Error");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnMovieWrError(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Slow Card");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnStorageSlow(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieOneSec(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	
	UISound_Play(DEMOSOUND_SOUND_SHUTTER_TONE);
	return WiFiCmd_OnMovieRawEncJpgOKCB(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieRawEncErr(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeEMRComplete(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
        CHKPNT;
		if((paramNum == 2)&&(paramArray[1] == MOVIE_USER_CB_EVENT_EMR_FILE_COMPLETED))
		{
			FlowWifiMovie_DrawLock(FALSE);
		}
		else if((paramNum == 2)&&(paramArray[1] == MOVIE_USER_CB_EVENT_CARSH_FILE_COMPLETED))
		{
			FlowWifiMovie_DrawLock(FALSE);
		}
		g_bRecordLock = FALSE;
		FlowMovie_DrawLock(FALSE);
		return NVTEVT_CONSUME;
  
}

INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n", __FUNCTION__);

	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Battery Low");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_BATTERY_LOW);
	return NVTEVT_CONSUME;
}
BOOL gbNoNeedVocieNotice = FALSE;
extern void System_ChangeToNormalMode(void);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.

	if(WiFiCmd_GetStatus() == WIFI_MOV_ST_RECORD)
		gbNoNeedVocieNotice = TRUE;
	
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0 || WIFI_UI_DIRECT_MOBILE_LINKOK == ENABLE)
	System_ChangeToNormalMode();
	//Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
#else
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), "No connect");
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	UINet_CliReConnect(1);
#endif
#endif
//#NT#2016/03/23#Isiah Chang -end
	return NVTEVT_CONSUME;

	//Ux_CloseWindow(pCtrl,0);

	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnExeMovieVedioReady(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiEvent;
	static UINT32 uiSyncTimeDelay = 0;
	extern 	BOOL bStartSyncTime;
    static UINT32 uiLEDDispCount;
	uiEvent = paramNum ? paramArray[0] : 0;

	switch (uiEvent) {
	case NVTEVT_SNAPSHOT_TIMER:
		GxTimer_StopTimer(&gUIWifiRawEncTimerID);
		WifiCmd_Done(WIFIFLAG_MOVIE_REC_RAWENC_DONE, WIFIAPP_RET_FAIL); 
		break;

	case NVTEVT_WIFI_TEST_KEY_TIMER1:
		GxTimer_StopTimer(&uiFactoryTestKeyTimerID);
		WifiCmd_Done(WIFIFLAG_TEST_KEY1_DONE,WIFIAPP_RET_TEST_KEY_TIMEOUT);
		break;

	case NVTEVT_WIFI_TEST_KEY_TIMER2:
		GxTimer_StopTimer(&uiFactoryTestKeyTimerID);
		WifiCmd_Done(WIFIFLAG_TEST_KEY2_DONE,WIFIAPP_RET_TEST_KEY_TIMEOUT);
		break;
		
	case NVTEVT_WIFI_TEST_KEY_TIMER3:
		GxTimer_StopTimer(&uiFactoryTestKeyTimerID);
		WifiCmd_Done(WIFIFLAG_TEST_KEY3_DONE,WIFIAPP_RET_TEST_KEY_TIMEOUT);
		break;
		
	case NVTEVT_WIFI_TEST_KEY_TIMER4:
		GxTimer_StopTimer(&uiFactoryTestKeyTimerID);
		WifiCmd_Done(WIFIFLAG_TEST_KEY4_DONE,WIFIAPP_RET_TEST_KEY_TIMEOUT);
		break;	
		
	case NVTEVT_WIFI_UI_TIMER:
		FlowWifiMovie_UpdateIconsOneSec();
		break;
	case NVTEVT_DISCONNECT_LAST_TIMER:
		UINet_AddACLTable();
		return NVTEVT_CONSUME;
	case NVTEVT_DELAY_CLOSE_TIMER: {
			//#NT#2016/03/08#Niven Cho -begin
			//#NT#because it is long time closing the linux-wifi, we don't change mode to movie video ahead.
			//#NT#use Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0),not post event
#if (WIFI_FUNC == ENABLE)
				INT32 curMode = System_GetState(SYS_STATE_CURRMODE);
				if ( curMode!= PRIMARY_MODE_MOVIE) {
			    	Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
					Ux_CloseWindow(&UIFlowWndMovieCtrl,0);
			    	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, curMode,SYS_SUBMODE_NORMAL);
				} else {
					VControl *pWnd =0 ;
					Ux_GetWindowByIndex(&pWnd, 1);

					Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
					System_ChangeSubMode(SYS_SUBMODE_NORMAL);
					Ux_CloseWindow(pWnd, 0);
				}
#endif
			//#NT#2016/03/08#Niven Cho -end
			return NVTEVT_CONSUME;
		}
    case NVTEVT_AUTO_REC_TIMER:		
		GxTimer_StopTimer(&gUIWifiAutoRecTimerID);
		if (WiFiCmd_GetStatus() != WIFI_MOV_ST_RECORD && System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE) 
        {
           Ux_PostEvent(NVTEVT_WIFI_EXE_MOVIE_REC, 1, 1);		
           WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STARTED);
        }
		break;
		
//#NT#2017/01/03#Isiah Chang -begin
//#NT#Add WiFiCmd Bitrate control.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0 || WIFI_UI_DIRECT_MOBILE_LINKOK == ENABLE)
	case NVTEVT_1SEC_TIMER: {
			WiFiCmd_HBOneSec();
			#if(USER_WATCH_DOG==ENABLE)
			SysFeedWDT();
			#endif
			return NVTEVT_CONSUME;
		}
#endif
//#NT#2017/01/03#Isiah Chang -end
	case NVTEVT_05SEC_TIMER: {
			//LED factory Test
			if(bLEDTestBegin && uiLEDDispCount < 6)
			{CHKPNT;
			   uiLEDDispCount ++;
			   if(LED_IsLEDOn(GPIOMAP_LED_MOVIE))
			   {
				   LED_TurnOffLED(GPIOMAP_LED_MOVIE);
			   }else{
				   LED_TurnOnLED(GPIOMAP_LED_MOVIE);
			   }
			}else
			{
			   bLEDTestBegin = FALSE;
			   uiLEDDispCount = 0;
			   if(!LED_IsLEDOn(GPIOMAP_LED_MOVIE))
				  LED_TurnOnLED(GPIOMAP_LED_MOVIE); 
			}
			if (g_uiRecordIngMotionDet == TRUE)
				WiFiCmd_OnMotionDetect();
			
			if(bStartSyncTime)
		    {
		      uiSyncTimeDelay ++;
			  if(uiSyncTimeDelay >= 4)
			  {
			     bStartSyncTime = FALSE;
			     System_SaveDateTime();
			  }
		    }
			return NVTEVT_CONSUME;
		}
	default:
		return NVTEVT_CONSUME;
	}
	return NVTEVT_CONSUME;
}

//长按关闭wifi
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
    if(bKey2TestBegin)
	{
	   WifiCmd_Done(WIFIFLAG_TEST_KEY2_DONE,WIFIAPP_RET_OK);
	   return NVTEVT_CONSUME;
    }
	return NVTEVT_CONSUME;
	
	UINT32  uiKeyAct;
	//UINT32  uiSoundMask;
	
	//static  BOOL keylock = FALSE;

	uiKeyAct = paramArray[0];

	switch (uiKeyAct) {
		case NVTEVT_KEY_CONTINUE:
			CHKPNT;
			//if(!keylock)
			{
				//keylock = TRUE;
				/*if (UI_GetData(FL_WIFI_LINK) != WIFI_LINK_OK) 
				{
					UISound_Play(DEMOSOUND_SOUND_WIFI_ON_TONE);
					BKG_PostEvent(NVTEVT_BKW_WIFI_ON);
					SysSetFlag(FL_AUTO_WIFI,AUTO_WIFI_ON);
				}
				else*/
				{
					//UISound_Play(DEMOSOUND_SOUND_WIFI_OFF_TONE);
					Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
					SysSetFlag(FL_AUTO_WIFI,AUTO_WIFI_OFF);
					UI_SetData(FL_WIFI,WIFI_OFF);
					Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, PRIMARY_MODE_MOVIE, SYS_SUBMODE_NORMAL);

				}
			}
			break;
			
		/*case NVTEVT_KEY_RELEASE:
			keylock = FALSE;
			break;*/
			
		default:
			break;
	}
	return NVTEVT_CONSUME;

	/*UINT32 result = WIFIAPP_RET_OK;
	
    if(bKey2TestBegin)
	{
	   WifiCmd_Done(WIFIFLAG_TEST_KEY2_DONE,WIFIAPP_RET_OK);
	   return NVTEVT_CONSUME;
    }

	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
		WifiCmd_Done(WIFIFLAG_PREVIEW_DONE, WIFIAPP_RET_STATE_ERR);
		return NVTEVT_CONSUME;
	}

	//680,510 media not record,also can raw encode
	if (ImageApp_MovieMulti_IsStreamRunning(_CFG_REC_ID_1) ||
		ImageApp_MovieMulti_IsStreamRunning(_CFG_REC_ID_2) ) {		
		if(FlowMovie_GetCurrRecTotalTime() > 3)
		{
		     _WifiMobileLinkOK_StartSnapShotTimer();
		    Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_RAWENC, 0);
		}
	} else {
		result = WIFIAPP_RET_FAIL;
		_WifiMobileLinkOK_StopSnapShotTimer();
		WifiCmd_Done(WIFIFLAG_MOVIE_REC_RAWENC_DONE, result); // signal wi-fi app cmd is done.
	}
*/
	return NVTEVT_CONSUME;

}

//开关录音
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
    if(bKey3TestBegin)
	{
	   WifiCmd_Done(WIFIFLAG_TEST_KEY3_DONE,WIFIAPP_RET_OK);
	   return NVTEVT_CONSUME;
    }
	return NVTEVT_CONSUME;
	
 	UINT32 uiEvtKeyAct = 0;

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];

    switch(uiEvtKeyAct)
    {
        case NVTEVT_KEY_PRESS:
			if (SysGetFlag(FL_MOVIE_AUDIO) == MOVIE_AUDIO_ON)
			{
				UISound_Play(DEMOSOUND_SOUND_AUDIO_OFF_TONE);
				SysSetFlag(FL_MOVIE_AUDIO,MOVIE_AUDIO_OFF);
			}
			else
			{
				UISound_Play(DEMOSOUND_SOUND_AUDIO_ON_TONE);
				SysSetFlag(FL_MOVIE_AUDIO,MOVIE_AUDIO_ON);
			}

			Ux_SendEvent(&CustomMovieObjCtrl,   NVTEVT_EXE_MOVIE_AUDIO, 1,  SysGetFlag(FL_MOVIE_AUDIO));
			//FlowWifiMovie_UpdateIcons(TRUE);
             break;
			 
        case NVTEVT_KEY_RELEASE:
        default:
            break;

    }
	return NVTEVT_CONSUME;
}

	
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
    if(bKey4TestBegin)
	{
	   WifiCmd_Done(WIFIFLAG_TEST_KEY4_DONE,WIFIAPP_RET_OK);
	   return NVTEVT_CONSUME;
    }
		//return NVTEVT_CONSUME;

    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
        case NVTEVT_KEY_PRESS:
			Ux_OpenWindow(&UIMenuWndWiFiMobileConfirmDisconnectCtrl,0);
           // Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);
            break;
    }
    Ux_DefaultEvent(pCtrl, NVTEVT_KEY_ENTER, paramNum, paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
	// Don't stop movie recording
	switch (gMovData.State) {
			
		case MOV_ST_REC:
		case MOV_ST_REC|MOV_ST_ZOOM:
			if (ImageApp_MovieMulti_IsStreamRunning(_CFG_REC_ID_1) ||
				ImageApp_MovieMulti_IsStreamRunning(_CFG_REC_ID_2) ) {		
				//if(FlowMovie_GetCurrRecTotalTime() > 3)
				{
				    _WifiMobileLinkOK_StartSnapShotTimer();
				    Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_RAWENC, 0);
				}
			}
			break;
			
		default:
			break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
    if(bKey1TestBegin)
	{
	   WifiCmd_Done(WIFIFLAG_TEST_KEY1_DONE,WIFIAPP_RET_OK);
	   return NVTEVT_CONSUME;
    }
	return NVTEVT_CONSUME;

	UINT32  uiKeyAct;
	//UINT32  uiSoundMask;

	uiKeyAct = paramArray[0];
	debug_msg("\r\nuiKeyAct:%d\r\n",uiKeyAct);
	
	if(gMovData.State == MOV_ST_REC)
	{
		if(!g_bRecordLock)
			return UIMenuWndWiFiMobileLinkOK_OnKeyCustom1(pCtrl,paramNum,paramArray);
	}
	
	Ux_DefaultEvent(pCtrl, NVTEVT_KEY_MENU, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
	
//智能语音抓拍处理
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyCapture(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 result = WIFIAPP_RET_OK;
	
    /*if(bKey2TestBegin)
	{
	   WifiCmd_Done(WIFIFLAG_TEST_KEY2_DONE,WIFIAPP_RET_OK);
	   return NVTEVT_CONSUME;
    }*/

	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
		WifiCmd_Done(WIFIFLAG_PREVIEW_DONE, WIFIAPP_RET_STATE_ERR);
		return NVTEVT_CONSUME;
	}

	//680,510 media not record,also can raw encode
	if (ImageApp_MovieMulti_IsStreamRunning(_CFG_REC_ID_1) ||
		ImageApp_MovieMulti_IsStreamRunning(_CFG_REC_ID_2) ) {		
		//if(FlowMovie_GetCurrRecTotalTime() > 3)
		{
		     _WifiMobileLinkOK_StartSnapShotTimer();
		    Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_RAWENC, 0);
		}
	} else {
		result = WIFIAPP_RET_FAIL;
		_WifiMobileLinkOK_StopSnapShotTimer();
		WifiCmd_Done(WIFIFLAG_MOVIE_REC_RAWENC_DONE, result); // signal wi-fi app cmd is done.
	}

	return NVTEVT_CONSUME;

}


BOOL bChangeMode = FALSE;

void _Wifi_StartAutoRecTimer(void)
{
	if (gUIWifiAutoRecTimerID == NULL_TIMER) {
	  gUIWifiAutoRecTimerID = GxTimer_StartTimer(3000, NVTEVT_AUTO_REC_TIMER, ONE_SHOT);
	}
}
extern void   WifiCmd_Lock(void);
extern void   WifiCmd_Unlock(void);
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 curMode = System_GetState(SYS_STATE_CURRMODE);

    if(bKey1TestBegin)
	{
	   WifiCmd_Done(WIFIFLAG_TEST_KEY1_DONE,WIFIAPP_RET_OK);
	   return NVTEVT_CONSUME;
    }
	
    if (curMode != PRIMARY_MODE_MOVIE) {
		
		WifiCmd_Unlock();
		WifiCmd_Done(0xffff,0);
		UINet_HFSUnInit();
		UINet_HFSInit();
		bChangeMode = TRUE;
        Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
        if (gUIWifiAutoRecTimerID == NULL_TIMER) {
          gUIWifiAutoRecTimerID = GxTimer_StartTimer(TIMER_TWO_SEC, NVTEVT_AUTO_REC_TIMER, ONE_SHOT);
        }
    }else{
        if (WiFiCmd_GetStatus() != WIFI_MOV_ST_RECORD){
           Ux_PostEvent(NVTEVT_WIFI_EXE_MOVIE_REC, 1, 1);		
           WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STARTED);
        }else{
           Ux_PostEvent(NVTEVT_WIFI_EXE_MOVIE_REC, 1, 0);
           WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STOPPED);
        }
	}
	return NVTEVT_CONSUME;

}

//智能语音录像处理
INT32 UIMenuWndWiFiMobileLinkOK_OnKeyLock(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (WiFiCmd_GetStatus() == WIFI_MOV_ST_RECORD){
		if (SysGetFlag(FL_MOVIE_URGENT_PROTECT_AUTO) == MOVIE_URGENT_PROTECT_AUTO_ON){		    
           #if (1)//_BOARD_DRAM_SIZE_ == 0x04000000)
			  UISound_Play(DEMOSOUND_SOUND_RECORD_LOCK_TONE);
              FlowWifiMovie_DrawLock(TRUE);
              //ImageApp_MovieMulti_SetCrash(_CFG_REC_ID_1, TRUE);
              
              	UINT32 i, mask, movie_rec_mask;             
				movie_rec_mask = Movie_GetMovieRecMask();
				mask = 1;
				for (i = 0; i < SENSOR_CAPS_COUNT; i++) {
					if (movie_rec_mask & mask) {
						ImageApp_MovieMulti_SetCrash(_CFG_REC_ID_1 + i, TRUE);
					}
					mask <<= 1;
				}
           #else
              UIVoice_Play(1, VOICE_EMERGENCY_RECORD);
			  UISound_Play(DEMOSOUND_SOUND_RECORD_LOCK_TONE);
              FlowWifiMovie_DrawLock(TRUE);
              ImageApp_MovieMulti_TrigEMR(_CFG_REC_ID_1);
           #endif
		}
	}else{
        if(!FlowMovie_IsStorageErr(FALSE)){
		   UISound_Play(DEMOSOUND_SOUND_RECORD_LOCK_TONE);
		   Ux_PostEvent(NVTEVT_WIFI_EXE_MOVIE_REC, 3, 1,0,UIAppWifiCmd_RecordLock);
		   FlowWifiMovie_DrawLock(TRUE);
        }
	}

	return NVTEVT_CONSUME;
}

extern BOOL bDemoStart;

INT32 UIMenuWndWiFiMobileLinkOK_OnKeyCustom1(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
	if(bDemoStart) 
		return NVTEVT_CONSUME;
	
	if (WiFiCmd_GetStatus() == WIFI_MOV_ST_RECORD) 
	{
		if (1)//(SysGetFlag(FL_MOVIE_URGENT_PROTECT_AUTO) == MOVIE_URGENT_PROTECT_AUTO_ON) 
		{		    
           #if (1)//_BOARD_DRAM_SIZE_ == 0x04000000)
			  UISound_Play(DEMOSOUND_SOUND_RECORD_LOCK_TONE);
              FlowWifiMovie_DrawLock(TRUE);
			  g_bRecordLock = TRUE;
			//ImageApp_MovieMulti_SetCrash(_CFG_REC_ID_1, TRUE);

			UINT32 i, mask, movie_rec_mask;             
			movie_rec_mask = Movie_GetMovieRecMask();
			mask = 1;
			for (i = 0; i < SENSOR_CAPS_COUNT; i++) {
				if (movie_rec_mask & mask) {
					ImageApp_MovieMulti_SetCrash(_CFG_REC_ID_1 + i, TRUE);
				}
				mask <<= 1;
			}
           #else
              UIVoice_Play(1, VOICE_EMERGENCY_RECORD);
			  UISound_Play(DEMOSOUND_SOUND_RECORD_LOCK_TONE);
              FlowWifiMovie_DrawLock(TRUE);
              ImageApp_MovieMulti_TrigEMR(_CFG_REC_ID_1);
           #endif
		}
	}
	else
	{
        if(!FlowMovie_IsStorageErr(FALSE) && (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE))
		{
		   UISound_Play(DEMOSOUND_SOUND_RECORD_LOCK_TONE);
		   Ux_PostEvent(NVTEVT_WIFI_EXE_MOVIE_REC, 3, 1,0,UIAppWifiCmd_RecordLock);
		   FlowWifiMovie_DrawLock(TRUE);
		   g_bRecordLock = TRUE;
        }
	}

	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey1Test(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    bKey1TestBegin = TRUE;
	
	if(uiFactoryTestKeyTimerID == NULL_TIMER)
	   uiFactoryTestKeyTimerID = GxTimer_StartTimer(10 * 1000, NVTEVT_WIFI_TEST_KEY_TIMER1, ONE_SHOT);
	
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey2Test(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    bKey2TestBegin = TRUE;
	
	if(uiFactoryTestKeyTimerID == NULL_TIMER)
	   uiFactoryTestKeyTimerID = GxTimer_StartTimer(10 * 1000, NVTEVT_WIFI_TEST_KEY_TIMER2, ONE_SHOT);

    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey3Test(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
    bKey3TestBegin = TRUE;
	
	if(uiFactoryTestKeyTimerID == NULL_TIMER)
	   uiFactoryTestKeyTimerID = GxTimer_StartTimer(10 * 1000, NVTEVT_WIFI_TEST_KEY_TIMER3, ONE_SHOT);
	
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeKey4Test(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
    bKey4TestBegin = TRUE;
	
	if(uiFactoryTestKeyTimerID == NULL_TIMER)
	   uiFactoryTestKeyTimerID = GxTimer_StartTimer(10 * 1000, NVTEVT_WIFI_TEST_KEY_TIMER4, ONE_SHOT);

    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeLEDTest(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    bLEDTestBegin = TRUE;
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    return NVTEVT_CONSUME;
}

extern BOOL bPlaybackChangeModeAutoRec;
extern BOOL bEnterTimelapse;
INT32 UIMenuWndWiFiMobileLinkOK_OnEnterAccOffTimelapse(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    BOOL CheckStorageErr;
	if( SysGetFlag(FL_MOVIE_CYCLIC_REC) == MOVIE_CYCLICREC_OFF )
	{
		CheckStorageErr = FlowMovie_IsStorageErr(TRUE);
	} 
	else 
	{
		CheckStorageErr = FlowMovie_IsStorageErr(FALSE);
	}
    if(CheckStorageErr)
    {
        debug_msg("^GLiwk ------ Card error ... Power off!!!\r\n");
        Ux_PostEvent(NVTEVT_KEY_POWER_REL, 1, NVTEVT_KEY_RELEASE);		
		return NVTEVT_CONSUME;
    }
	//ide_setTvPowerDown(TRUE);
    bEnterTimelapse = TRUE;
	bPlaybackChangeModeAutoRec = TRUE;
	if (SysGetFlag(FL_MOVIE_TIMELAPSE_REC)==MOVIE_TIMELAPSEREC_OFF)
		SysSetFlag(FL_MOVIE_TIMELAPSE_REC,MOVIE_TIMELAPSEREC_1SEC);
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, PRIMARY_MODE_MOVIE, SYS_SUBMODE_NORMAL);
	Ux_SendEvent(0, NVTEVT_EXE_WIFI_STOP, 0);
	return NVTEVT_CONSUME;
}

//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkSts)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyMode(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Button_Disconnect)
EVENT_ITEM(NVTEVT_KEY_SELECT, UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter)
//EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyMode)
EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
		return NVTEVT_CONSUME;
	}
#endif
//#NT#2016/05/31#Ben Wang -end
#if (WIFI_FUNC == ENABLE)
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	//notify current connected socket,new connect not get IP and socket not create
	//cannot disconnet immediate,suggest after 500 ms
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
	//delay 500 ms,and then close window
	//in window,use GxTimer replace Timer Delay,it would occupat UI task
	GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DELAY_CLOSE_TIMER, ONE_SHOT);
#else

	System_ChangeToNormalMode();
	//should close network application,then stop wifi
	Ux_SendEvent(0, NVTEVT_EXE_WIFI_STOP, 0);

#endif
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
	//#NT#2016/03/23#Isiah Chang -begin
	//#NT#add new Wi-Fi UI flow.


	    UISound_Play(DEMOSOUND_SOUND_WIFI_OFF_TONE);
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0 || WIFI_UI_DIRECT_MOBILE_LINKOK == ENABLE)
		Ux_SendEvent(0, NVTEVT_EXE_WIFI_STOP, 0);
		UIMenuWndWiFiMobileLinkOK_SyncRecStatus();
        System_ChangeToNormalMode();
		SysSetFlag(FL_AUTO_WIFI,AUTO_WIFI_OFF);
		//_Movie_StartAutoRecTimer();
#else
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), "No connect");
		UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
		UINet_CliReConnect(1);
#endif
#endif
	//#NT#2016/03/23#Isiah Chang -end
		return NVTEVT_CONSUME;
	
		//Ux_CloseWindow(pCtrl,0);
}

//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_MAC)
EVENT_END
//----------------------UIMenuWndWiFiMobileLinkOK_Static_cameraCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_camera)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_WIFICtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_WIFI)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_timeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_time)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_resolutionCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_resolution)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_StorageCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Storage)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_CyclicRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_CyclicRec)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusICN_EVCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusICN_EV)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_YMD_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_YMD_Static)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_HMS_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_HMS_Static)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_RECCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_REC)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_LockCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Lock)
EVENT_END


extern INT32 UIFlowWndMovie_ALG_Draw_OSD(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
//---------------------UIFlowWndMovie_ALG_DrawCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_ALG_Draw)
CTRL_LIST_END
//----------------------UIFlowWndMovie_ALG_DrawCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_ALG_Draw_OnRedraw(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_ALG_Draw)
EVENT_ITEM(NVTEVT_REDRAW, UIMenuWndWiFiMobileLinkOK_ALG_Draw_OnRedraw)
EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_ALG_Draw_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndMovie_ALG_Draw_OSD(pCtrl, paramNum, paramArray);
}
