//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONITEM_H
#define MENUCOMMONITEM_H

#include "UIFramework.h"

extern VControl MenuCommonItemCtrl;//Panel type 

extern VControl MenuCommonItem_BGTitleBarCtrl;//Panel type 

extern VControl MenuCommonItem_BGMenuCtrl;//Panel type 

extern VControl MenuCommonItem_TitleBarCtrl;//Panel type 

extern VControl Tab91Ctrl;//Tab type 

typedef enum
{
Tab91_Button92,
Tab91_Button93,
Tab91_MAX
}Tab91_Setting;

extern VControl Button92Ctrl;//Button type 

extern VControl Button93Ctrl;//Button type 

extern VControl MenuCommonItem_TitleBarStatusIconCtrl;//Status type 

typedef enum
{
MenuCommonItem_TitleBarStatusIcon_ICON_MENU_VIDEO_OFF,
MenuCommonItem_TitleBarStatusIcon_ICON_MENU_STILL_OFF,
MenuCommonItem_TitleBarStatusIcon_ICON_MENU_PLAYBACK_OFF,
MenuCommonItem_TitleBarStatusIcon_MAX
}MenuCommonItem_TitleBarStatusIcon_Setting;

extern VControl MenuCommonItem_MenuCtrl;//Menu type 

#if 1
typedef enum
{
	resolution = 0, // 分辨率 
	cyclerec,// 循环录影
	wdr,// WDR	
	exposure,// 曝光补偿 
	gravitysensor,// 重力感应	
	recaudio,// 录影音频 
	datestamp// 日期标签 
		
}VideoItem;

typedef enum
{
	wifi,//wifi 
	datetime,// 日期时间 
	language,// 语言设置 
	keysound,// 按键声音 
	screenpro,// 屏幕保护 	
	lowbattpro,// 低电保护 	
	timelapse,// 缩时录影 	
    frequency,//光源频率
	parkingmode,// // 停车模式 	
	motiondet,// 移动侦测	
	format,// 格式化 
	defaultsetup,// 默认设置 
	gpsInfo,//GPS信息
	version// 版本

}SetupItem;

typedef enum
{
	timer,//定时
	resolution_photo,// 分辨率
	cap_burst,// 连拍
	compression,// 图像质量 
	sharpness,// 锐度 	
       white_balance,//白平衡
	iso,// // iso
	exposure_photo,// 曝光补偿
	anti_shaking,// 防手震
	quick_review,// 快速预览
	datestamp_photo// 日期标签

}PhotoItem;

typedef enum
{

	volume,// 音量调节
	delete_playback,// 删除
	protect// 保护

}PlayBackItem;

#endif

typedef enum
{
MenuCommonItem_Menu_STRID_A0,
MenuCommonItem_Menu_STRID_A1,
MenuCommonItem_Menu_STRID_A2,
MenuCommonItem_Menu_STRID_A3,
MenuCommonItem_Menu_STRID_A4,
MenuCommonItem_Menu_STRID_A5,
MenuCommonItem_Menu_STRID_A6,
MenuCommonItem_Menu_STRID_A7,
MenuCommonItem_Menu_STRID_A8,
MenuCommonItem_Menu_STRID_A9,
MenuCommonItem_Menu_STRID_B0,
MenuCommonItem_Menu_STRID_B1,
MenuCommonItem_Menu_STRID_B2,
MenuCommonItem_Menu_STRID_B3,
MenuCommonItem_Menu_STRID_B4,
MenuCommonItem_Menu_STRID_B5,
MenuCommonItem_Menu_STRID_B6,
MenuCommonItem_Menu_STRID_B7,
MenuCommonItem_Menu_STRID_B8,
MenuCommonItem_Menu_STRID_B9,
MenuCommonItem_Menu_MAX
}MenuCommonItem_Menu_Setting; 

//---------------------MenuCommonItemCtrl User Export---------------------------
#endif
