//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonItemRes.c"
#include "MenuCommonItem.h"
#include "PrjCfg.h"
#include "UIFlow.h"
#include "UIInfo.h"
#include "UIMenuWndSetupVersion.h"
#include "UIMenuWndSetupDefaultSetting.h"
#include "UIMenuWndPhotoExposure.h"
#include "UIMenuWndSetupFormatConfirm.h"
#include "UIMenuWndSetupVersion.h"

extern UINT32 System_GetEnableSensor(void);

//---------------------MenuCommonItemCtrl Debug Definition -----------------------------
#define _MENUCOMMONITEM_ERROR_MSG        1
#define _MENUCOMMONITEM_TRACE_MSG        0

#if (_MENUCOMMONITEM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonItemErrMsg(...)            debug_msg ("^R MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemErrMsg(...)
#endif

#if (_MENUCOMMONITEM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonItemTraceMsg(...)          debug_msg ("^B MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemTraceMsg(...)
#endif

//---------------------MenuCommonItemCtrl Global Variables -----------------------------
#define PAGE           4
//---------------------MenuCommonItemCtrl Prototype Declaration  -----------------------
#if defined(_KEY_METHOD_4KEY_)
#define MENU_KEY_PRESS_MASK        (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_MODE|FLGKEY_ENTER|FLGKEY_MENU|FLGKEY_SHUTTER2)
#define MENU_KEY_RELEASE_MASK      (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_MODE|FLGKEY_ENTER|FLGKEY_MENU|FLGKEY_SHUTTER2)
#define MENU_KEY_CONTINUE_MASK     (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_RIGHT|FLGKEY_SHUTTER2)
#else
#define MENU_KEY_PRESS_MASK        (FLGKEY_LEFT|FLGKEY_RIGHT)
#define MENU_KEY_RELEASE_MASK      (FLGKEY_LEFT|FLGKEY_RIGHT)
#define MENU_KEY_CONTINUE_MASK     (FLGKEY_LEFT|FLGKEY_RIGHT)
#endif
//---------------------MenuCommonItemCtrl Public API  ----------------------------------

//---------------------MenuCommonItemCtrl Private API  ---------------------------------
#define  VideoItem 7
#define SetupItem 14//13
void MenuCommonItem_funupdate(void)
{
	 UINT32 CurTabIndex = UxTab_GetData(&Tab91Ctrl,TAB_FOCUS );
	if (CurTabIndex == 0 )
	{

	}
	debug_msg("\r\n CurTabIndex:%d ", CurTabIndex);
	switch( CurTabIndex ) //(CurItem)
	{
		case Tab91_Button92://video:
		if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)
			{
					      UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_TOTITM, 7);					
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_STRID, 
						STRID_IMGSIZE);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_ICONID, 
						ICON_RESOLUTION);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_STRID, 
						STRID_CYCLIC_REC);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_ICONID, 
						ICON_REC_RECOVERY);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_STRID, 
						STRID_WDR );
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_ICONID, 
						ICON_MENU_WDR);


						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 3, MNUITM_STRID, 
						STRID_EXPOSURE );
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 3, MNUITM_ICONID, 
						ICON_EV);

						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 4, MNUITM_STRID, 
						STRID_GRAVITYSENSOR);  
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 4, MNUITM_ICONID, 
						ICON_G_SENSOR);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 5, MNUITM_STRID, 
						STRID_RECORD_AUDIO);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 5, MNUITM_ICONID, 
						ICON_SOUND_REC_ON);

						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 6, MNUITM_STRID, 
						STRID_DATE_STAMP ); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 6, MNUITM_ICONID, 
						ICON_DATE_PRINT);

					
			}
  else if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PHOTO)		
  	{
  						UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_TOTITM, 11); 
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_STRID, STRID_CAP_TIMER);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_ICONID, 
						ICON_DATE_TIME);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_STRID, STRID_IMGSIZE );
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_ICONID, 
						ICON_RESOLUTION);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_STRID, STRID_CAP_BURST);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_ICONID, 
						ICON_BUST);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 3, MNUITM_STRID, STRID_COMPRESSION);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 3, MNUITM_ICONID, 
						ICON_QUALITY);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 4, MNUITM_STRID, STRID_SHARPNESS); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 4, MNUITM_ICONID, 
						ICON_SHARPNESS);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 5, MNUITM_STRID, STRID_WB); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 5, MNUITM_ICONID, 
						ICON_WB);	
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 6, MNUITM_STRID, STRID_ISO); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 6, MNUITM_ICONID, 
						ICON_ISO); 		

						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 7, MNUITM_STRID, STRID_EXPOSURE); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 7, MNUITM_ICONID, 
						ICON_EV);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 8, MNUITM_STRID, STRID_ANTI_SHAKING);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 8, MNUITM_ICONID, 
						ICON_SHAKE_ON);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 9, MNUITM_STRID, STRID_QUICK_VIEW);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 9, MNUITM_ICONID, 
						ICON_QUICK_REVIEW);  

						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 10, MNUITM_STRID, STRID_DATE_STAMPING);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 10, MNUITM_ICONID, 
						ICON_DATE_PRINT);  						
  	}

  	else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK)
			{
					      UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_TOTITM, 3);					
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_STRID, 
						STRID_VOLUME);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_ICONID, 
						ICON_VOICE);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_STRID, 
						STRID_DELETE);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_ICONID, 
						ICON_DELETE);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_STRID, 
						STRID_PROTECT );
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_ICONID, 
						ICON_PROTECT);
					
			}
					break; 
		case Tab91_Button93://setup:
		
					UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_TOTITM, SetupItem);
					// menut item 
					{
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_STRID, STRID_WIFI );
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 0, MNUITM_ICONID, 
						ICON_WIFI_DOT_CONNECTING_ON);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_STRID, STRID_DATE_TIME );
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 1, MNUITM_ICONID, 
						ICON_DATETIME_SETUP);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_STRID, STRID_LANGUAGE);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 2, MNUITM_ICONID, 
						ICON_LANGUAGE);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 3, MNUITM_STRID, STRID_BEEPER);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 3, MNUITM_ICONID, 
						ICON_SPEAKER);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 4, MNUITM_STRID, STRID_SCREEN_PRO); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 4, MNUITM_ICONID, 
						ICON_SCREENSAVER);

						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 5, MNUITM_STRID, STRID_LOWBATTERY_PRO); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 5, MNUITM_ICONID, 
						ICON_POWER_OFF);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 6, MNUITM_STRID, STRID_TIMELAPSE_SET); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 6, MNUITM_ICONID, 
						ICON_TIME_LAPSE_ON);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 7, MNUITM_STRID, STRID_FREQUENCY); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 7, MNUITM_ICONID, 
						ICON_HZ);	
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 8, MNUITM_STRID, STRID_PARK_MONITOR); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 8, MNUITM_ICONID, 
						ICON_PARKING);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 9, MNUITM_STRID, STRID_MOTION_DET); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 9, MNUITM_ICONID, 
						ICON_MOTION_DET_ON); 	
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 10, MNUITM_STRID, STRID_FORMAT); 
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 10, MNUITM_ICONID, 
						ICON_FORMAT);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 11, MNUITM_STRID, STRID_DEFAULT_SETTING);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 11, MNUITM_ICONID, 
						ICON_DEFAULT);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 12, MNUITM_STRID, STRID_GPS_INFO);
					    UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 12, MNUITM_ICONID, 
						ICON_INFO);
						
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 13, MNUITM_STRID, STRID_VERSION);
						UxMenu_SetItemData(&MenuCommonItem_MenuCtrl, 13, MNUITM_ICONID, 
						ICON_FIRMWARE_UPDATE);
					}
					
					break;
		default:
					
					break;
					

	}
}

//---------------------MenuCommonItemCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem)
CTRL_LIST_ITEM(MenuCommonItem_BGTitleBar)
CTRL_LIST_ITEM(MenuCommonItem_BGMenu)
CTRL_LIST_ITEM(MenuCommonItem_TitleBar)
CTRL_LIST_ITEM(MenuCommonItem_Menu)
CTRL_LIST_END

//----------------------MenuCommonItemCtrl Event---------------------------
INT32 MenuCommonItem_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnKeyMode(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(MenuCommonItem)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, MenuCommonItem_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, MenuCommonItem_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, MenuCommonItem_OnChildClose)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, MenuCommonItem_OnStorageChange)
//EVENT_ITEM(NVTEVT_KEY_DOWN,MenuCommonItem_OnKeyDown)
//EVENT_ITEM(NVTEVT_KEY_UP,MenuCommonItem_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_ENTER,MenuCommonItem_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,MenuCommonItem_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,MenuCommonItem_OnKeyMode)
EVENT_END


INT32 MenuCommonItem_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0 
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;
	TM_ITEM    *pItem;
	TM_OPTION  *pOption;
	TM_ITEM    *pModeItem;
	INT32      curMode = 0;

	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_CONTINUE_MASK);

	if (UI_GetData(FL_WIFI_LINK) == WIFI_LINK_OK && UI_GetData(FL_NetWorkMode) == NET_STATION_MODE) {
		SysSetFlag(FL_COMMON_CLOUD, CLOUD_ON);
	} else {
		SysSetFlag(FL_COMMON_CLOUD, CLOUD_OFF);
	}

	if (System_GetEnableSensor() == (SENSOR_1 | SENSOR_2)) {
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_ENABLE);
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_ENABLE);
#if (_BOARD_DRAM_SIZE_ == 0x04000000)
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1280x720P30, TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_848x480P30, TM_OPTION_ENABLE);
#else
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_ENABLE);
#endif
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P80, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60, TM_OPTION_DISABLE);
	} else {
#if (SENSOR_CAPS_COUNT > 1)
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_DISABLE);
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_DISABLE);
#endif
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_DISABLE);
		//#NT#2016/08/12#Hideo Lin -begin
		//#NT#For small size clone movie
#if (SMALL_CLONE_MOVIE == DISABLE)
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P80, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60, TM_OPTION_DISABLE);
#endif
		//#NT#2016/08/12#Hideo Lin -end
	}

	MenuCommonItem_SetCurrentMenu(&gCommonMenu);
	pMenu = MenuCommonItem_GetCurrentMenu();

	pMenu->Status = TMS_ON_ITEM;
	pMenu->SelPage = 0;         // reset page to 0

	pPage = &pMenu->pPages[pMenu->SelPage];
	pPage->SelItem = 0;           // reset item to 0
	//check item if disable
	TM_CheckItemStatus(pMenu, &pPage->SelItem, TRUE);

	pItem = &pPage->pItems[pPage->SelItem];
	pOption = &pItem->pOptions[SysGetFlag(pItem->SysFlag)];

//	UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  pOption->TextId);
//	UxList_SetData(&MenuCommonItem_ListCtrl, LST_CURITM, 0);

	curMode = System_GetState(SYS_STATE_CURRMODE);
	if (curMode == PRIMARY_MODE_PHOTO) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_CAPTURE_M;
		pModeItem->TextId = STRID_CAP_MODE;
	} else if (curMode == PRIMARY_MODE_MOVIE) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_VIDEO_M;
		pModeItem->TextId = STRID_MOVIE;
	} else if (curMode == PRIMARY_MODE_PLAYBACK) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_PLAYBACK_M;
		pModeItem->TextId = STRID_PLAYBACK;
	}

	MenuCommonItem_UpdateContent(pMenu);
	MenuCommonItem_UpdatePosition();
    
	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_PRESS_MASK);
	Input_SetKeySoundMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
    
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);

	return NVTEVT_CONSUME;
#endif
	CHKPNT;
	//TM_MENU    *pMenu;
   	UxTab_SetData(&Tab91Ctrl, TAB_FOCUS, Tab91_Button92);

    UxMenu_SetData(&MenuCommonItem_MenuCtrl,MNU_CURITM,0);
if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)	
{
     UxState_SetData(&MenuCommonItem_TitleBarStatusIconCtrl,STATE_CURITEM,MenuCommonItem_TitleBarStatusIcon_ICON_MENU_VIDEO_OFF);	
	UxMenu_SetData(&MenuCommonItem_MenuCtrl,MNU_TOTITM,7);
	
}
else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PHOTO) 
{
     UxState_SetData(&MenuCommonItem_TitleBarStatusIconCtrl,STATE_CURITEM,MenuCommonItem_TitleBarStatusIcon_ICON_MENU_STILL_OFF);	
	UxMenu_SetData(&MenuCommonItem_MenuCtrl,MNU_TOTITM,11);
}
else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) 
{
     UxState_SetData(&MenuCommonItem_TitleBarStatusIconCtrl,STATE_CURITEM,MenuCommonItem_TitleBarStatusIcon_ICON_MENU_PLAYBACK_OFF);	
	UxMenu_SetData(&MenuCommonItem_MenuCtrl,MNU_TOTITM,3);	
}
	MenuCommonItem_funupdate();
	UxCtrl_IsShow(&MenuCommonItemCtrl);
     UxCtrl_SetShow(&MenuCommonItem_TitleBarStatusIconCtrl, TRUE);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
	

}
INT32 MenuCommonItem_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
/*
	Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_MASK_DEFAULT);

	//#NT#2016/08/19#Lincy Lin#[0106935] -begin
	//#NT# Support change WDR, SHDR, RSC setting will change mode after exit menu
	BOOL bReOpenMovie = FlowMovie_CheckReOpenItem();
	BOOL bReOpenPhoto = 0;
#if (PHOTO_MODE==ENABLE)
	bReOpenPhoto = FlowPhoto_CheckReOpenItem();
#endif
	if(bReOpenMovie)
		exam_msg("RESTART_MODE_YES\r\n");
	else
		exam_msg("RESTART_MODE_NO\r\n");

	if (bReOpenMovie || bReOpenPhoto)
		//#NT#2016/08/19#Lincy Lin -end
	{
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
	}
*/
 //FLowMovie_TX_SYSMenuSetting();
#if 0
	ETHCAM_MENU_SETTING sEthCamMenuSetting[ETH_REARCAM_CAPS_COUNT]={0};
	for(j=0;j<ETH_REARCAM_CAPS_COUNT;j++){
		if(socketCliEthCmd_IsConn(j) && EthCamNet_GetEthLinkStatus(j)==ETHCAM_LINK_UP){
			CHKPNT;
			EthCam_SendXMLCmd(j, ETHCAM_PORT_DEFAULT ,ETHCAM_CMD_SYNC_MENU_SETTING, 0);
		#if (ETH_REARCAM_CAPS_COUNT>=2)
			sEthCamMenuSetting[j].Size=MOVIE_SIZE_FRONT_1920x1080P30;//MOVIE_SIZE_CLONE_1920x1080P30_1280x720P60;//UI_GetData(FL_MOVIE_SIZE);
		#else
			sEthCamMenuSetting[j].Size=MOVIE_SIZE_CLONE_1920x1080P30_1280x720P30;//UI_GetData(FL_MOVIE_SIZE);
		#endif
			sEthCamMenuSetting[j].WDR=UI_GetData(FL_MOVIE_WDR);
			sEthCamMenuSetting[j].EV=UI_GetData(FL_EV);
			sEthCamMenuSetting[j].DateImprint=UI_GetData(FL_MOVIE_DATEIMPRINT);
			sEthCamMenuSetting[j].SensorRotate=UI_GetData(FL_MOVIE_SENSOR_ROTATE);
			sEthCamMenuSetting[j].Codec=MOVIE_CODEC_H264;//UI_GetData(FL_MOVIE_CODEC);
			sEthCamMenuSetting[j].TimeLapse=MOVIE_TIMELAPSEREC_OFF;//UI_GetData(FL_MOVIE_TIMELAPSE_REC);
			DBG_DUMP("Size=%d\r\n", sEthCamMenuSetting[j].Size);
			EthCam_SendXMLData(j, (UINT8 *)&sEthCamMenuSetting[j], sizeof(ETHCAM_MENU_SETTING));
		}

	}
#endif
	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
	TM_MENU    *pMenu = MenuCommonItem_GetCurrentMenu();
	//UINT32      uiItem ,uiOption;

	pMenu->Status = TMS_ON_ITEM;
	MenuCommonItem_UpdateContent(pMenu);
	MenuCommonItem_UpdatePosition();
	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
	Ux_DefaultEvent(pCtrl, NVTEVT_CHILD_CLOSE, paramNum, paramArray);

	if (paramNum >= 2) {
		//uiItem = paramArray[0];
		//uiOption = paramArray[1];
	}
	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_CONTINUE_MASK);

	return NVTEVT_CONSUME;
#endif

    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);	
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnOpenVideo(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
	UINT32 CurMenuItem = paramArray[0];
	debug_msg("\r\nOnKeySelect  CurTabIndex:%d \r\n", CurMenuItem);
	switch(CurMenuItem)	
	{
		case resolution: 
			Ux_OpenWindow(&UIMenuWndSetupResolutionCtrl, 0);

		break;
		
		case cyclerec:
			Ux_OpenWindow(&UIMenuWndSetupCycleRecCtrl,0);
			break;

		case wdr:
			Ux_OpenWindow(&UIMenuWndSetupWDRCtrl, 0); 
			break;
			
		case exposure:
			Ux_OpenWindow(&UIMenuWndPhotoExposureCtrl,0);
			break;
			
		case  gravitysensor:
			Ux_OpenWindow(&UIMenuWndSetupGsensorCtrl,0);
			break;	
			
		case recaudio:
			Ux_OpenWindow(&UIMenuWndSetupMovieAudioCtrl,0);	
			break;
			
		case datestamp:
			Ux_OpenWindow(&UIMenuWndSetupMovieDetStampCtrl,0);			
			break;
			
			
		default:
			break;
	}
	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnOpenSetup(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 CurMenuItem = paramArray[0];
	debug_msg("\r\nOnKeySelect  CurTabIndex:%d \r\n", CurMenuItem);

	switch(CurMenuItem)
	{

		case wifi: 
			//Ux_OpenWindow(&UIMenuWndSetupWifiCtrl, 0); // 需要修改各个界面关闭时不要进入menuitem界面就好
			Ux_OpenWindow(&UIMenuWndSetupWifiCtrl, 1,0); 
			break;
			
		case datetime: 
			Ux_OpenWindow(&UIMenuWndSetupDateTimeCtrl, 0);
			break;
			
		case language:
			Ux_OpenWindow(&UIMenuWndSetupLanguageCtrl, 0);
			break;

		case keysound:
			Ux_OpenWindow(&UIMenuWndSetupKeySoundCtrl, 0);
			break;
			
		case screenpro:
			Ux_OpenWindow(&UIMenuWndSetupScreenProCtrl, 0);
			break;
			
		case lowbattpro:
			Ux_OpenWindow(&UIMenuWndSetupLowBatteryProCtrl, 0);//新增低电保护设定
			break;

		case timelapse:
			Ux_OpenWindow(&UIMenuWndSetupTimeLapseCtrl, 0);//新增缩时录影设定
			break;
			
		case frequency:
			Ux_OpenWindow(&UIMenuWndSetupFrequencyCtrl, 0);
			break;

		case parkingmode:
			Ux_OpenWindow(&UIMenuWndSetupParkingCtrl, 0);
			break;
			
		case motiondet: 
			Ux_OpenWindow(&UIMenuWndSetupWifiCtrl, 1, 1); 
			break;	
			
		case format:
			Ux_OpenWindow(&UIMenuWndSetupFormatConfirmCtrl,0);
			break;
			
		case defaultsetup:
			Ux_OpenWindow(&UIMenuWndSetupDefaultSettingCtrl,0);
			break;
			
		case gpsInfo:
			Ux_OpenWindow(&UIMenuWndSetupGPS_INFOCtrl,0);
			break;
			
		case version:
			Ux_OpenWindow(&UIMenuWndSetupVersionCtrl,0);
			break;
		default:
			break;
	}
	return NVTEVT_CONSUME;
}


INT32 MenuCommonItem_OnOpenPhoto(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 CurMenuItem = paramArray[0];
	debug_msg("\r\nOnKeySelect  CurTabIndex:%d \r\n", CurMenuItem);

	switch(CurMenuItem)
	{

		case timer: 
			Ux_OpenWindow(&UIMenuWndPhotoTimerCtrl, 0); // 需要修改各个界面关闭时不要进入menuitem界面就好
			break;
			
		case resolution_photo: 
			Ux_OpenWindow(&UIMenuWndPhotoSizeCtrl, 0);
			break;
			
		case cap_burst:
			Ux_OpenWindow(&UIMenuWndPhotoBurstCtrl, 0);
			break;

		case compression:
			Ux_OpenWindow(&UIMenuWndPhotoCompressionCtrl, 0);
			break;
			
		case sharpness:
			Ux_OpenWindow(&UIMenuWndPhotoSharpnessCtrl, 0);
			break;
			
		case white_balance:
			Ux_OpenWindow(&UIMenuWndPhotoWBCtrl, 0);
			break;

		case iso:
			Ux_OpenWindow(&UIMenuWndPhotoIsoCtrl, 0);
			break;	
			
		case  exposure_photo:
				Ux_OpenWindow(&UIMenuWndPhotoExposureCtrl,0);
			break;
			
		case anti_shaking:
			Ux_OpenWindow(&UIMenuWndPhotoAnti_ShakingCtrl,0);
			break;
			
		case quick_review:
			Ux_OpenWindow(&UIMenuWndPhotoQuick_ReviewCtrl,0);
			break;
			
		case datestamp_photo:
			Ux_OpenWindow(&UIMenuWndPhotoDateStampCtrl,0);
			break;			
		default:
			break;
	}
	return NVTEVT_CONSUME;
}



INT32 MenuCommonItem_OnOpenPlayBack(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 CurMenuItem = paramArray[0];
	debug_msg("\r\nOnKeySelect  CurTabIndex:%d \r\n", CurMenuItem);

	switch(CurMenuItem)
	{

		case volume: 
			Ux_OpenWindow(&UIMenuWndPlayVolumeCtrl, 0); // 需要修改各个界面关闭时不要进入menuitem界面就好
			break;
			
		case delete_playback: 
			Ux_OpenWindow(&UIMenuWndPlayDelCtrl, 0);
			break;
			
		case protect:
			Ux_OpenWindow(&UIMenuWndPlayProtectCtrl, 0);
			break;	
		default:
			break;
	}
	return NVTEVT_CONSUME;
}


INT32 MenuCommonItem_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif
	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
       //UINT32 uiEvtKeyAct = 0;
	UINT32 CurTabIndex = UxTab_GetData(&Tab91Ctrl,TAB_FOCUS );
	UINT32 CurMenuItem = UxMenu_GetData(&MenuCommonItem_MenuCtrl, MNU_CURITM); 

	debug_msg("\r\nOnKeySelect  CurTabIndex:%d  %d\r\n", CurTabIndex,CurMenuItem);
	switch (CurTabIndex)
	{
        case Tab91_Button92:
		if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)			
			MenuCommonItem_OnOpenVideo(pCtrl, 1, &CurMenuItem);
		else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PHOTO)			
			MenuCommonItem_OnOpenPhoto(pCtrl, 1, &CurMenuItem);	
		else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK)			
			MenuCommonItem_OnOpenPlayBack(pCtrl, 1, &CurMenuItem);			
             break;
        case Tab91_Button93:
			MenuCommonItem_OnOpenSetup(pCtrl, 1, &CurMenuItem);
			break;
        default:
            break;

    }
        return NVTEVT_CONSUME;

}
INT32 MenuCommonItem_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	UINT32 uiEvtKeyAct = 0;
	UINT32 CurTabIndex = UxTab_GetData(&Tab91Ctrl,TAB_FOCUS );
	debug_msg("\r\n CurTabIndex: %d ", CurTabIndex);

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];

	 switch(CurTabIndex )
	 {
		case Tab91_Button92:
			Ux_SendEvent(&Tab91Ctrl,NVTEVT_NEXT_ITEM,0);
			MenuCommonItem_funupdate();
			UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_CURITM, 0);
			if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)	
			{
			     UxState_SetData(&MenuCommonItem_TitleBarStatusIconCtrl,STATE_CURITEM,MenuCommonItem_TitleBarStatusIcon_ICON_MENU_VIDEO_OFF);		
			}
			else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PHOTO) 
			{
			     UxState_SetData(&MenuCommonItem_TitleBarStatusIconCtrl,STATE_CURITEM,MenuCommonItem_TitleBarStatusIcon_ICON_MENU_STILL_OFF);	
			}
			else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) 
			{
			     UxState_SetData(&MenuCommonItem_TitleBarStatusIconCtrl,STATE_CURITEM,MenuCommonItem_TitleBarStatusIcon_ICON_MENU_PLAYBACK_OFF);	
			}
            UxCtrl_SetShow(&MenuCommonItem_TitleBarStatusIconCtrl, TRUE);
					
			break;
		case Tab91_Button93:
			UxMenu_SetData(&MenuCommonItem_MenuCtrl, MNU_CURITM, 0);			
			MenuCommonItem_funupdate();
			Ux_CloseWindow(& MenuCommonItemCtrl,0);
			//Save_MenuInfo();			
			break;		
		default:
			break;
	 }

    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{CHKPNT;
	Ux_CloseWindow(& MenuCommonItemCtrl,0);
 //   Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_MenuCtrl Event---------------------------
INT32 MenuCommonItem_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,MenuCommonItem_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,MenuCommonItem_Menu_OnKeyDown)
EVENT_END

INT32 MenuCommonItem_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiEvtKeyAct = 0;

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];

    switch(uiEvtKeyAct)
    {
        case NVTEVT_KEY_PRESS:
			Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
             break;
        case NVTEVT_KEY_RELEASE:
        default:
            break;
    }
    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32 uiEvtKeyAct = 0;

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];

    switch(uiEvtKeyAct)
    {
        case NVTEVT_KEY_PRESS:
			Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
             break;
        case NVTEVT_KEY_RELEASE:
        default:
            break;

    }         
    return NVTEVT_CONSUME;
}


//---------------------MenuCommonItem_BGTitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_BGTitleBar)
CTRL_LIST_END

//----------------------MenuCommonItem_BGTitleBarCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BGTitleBar)
EVENT_END

//---------------------MenuCommonItem_BGMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_BGMenu)
CTRL_LIST_END

//----------------------MenuCommonItem_BGMenuCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BGMenu)
EVENT_END

//---------------------MenuCommonItem_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_TitleBar)
CTRL_LIST_ITEM(Tab91)
CTRL_LIST_ITEM(MenuCommonItem_TitleBarStatusIcon)
CTRL_LIST_END

//----------------------MenuCommonItem_TitleBarCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TitleBar)
EVENT_END

//----------------------Tab91Ctrl Event---------------------------
EVENT_BEGIN(Tab91)
EVENT_END

//----------------------Button92Ctrl Event---------------------------
EVENT_BEGIN(Button92)
EVENT_END

//----------------------Button93Ctrl Event---------------------------
EVENT_BEGIN(Button93)
EVENT_END

//----------------------MenuCommonItem_TitleBarStatusIconCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_TitleBarStatusIcon)
EVENT_END
